-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity activation_accelerator_lut_erf is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of activation_accelerator_lut_erf is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_40800000 : STD_LOGIC_VECTOR (31 downto 0) := "01000000100000000000000000000000";
    constant ap_const_lv32_41FEFF0F : STD_LOGIC_VECTOR (31 downto 0) := "01000001111111101111111100001111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_C0800000 : STD_LOGIC_VECTOR (31 downto 0) := "11000000100000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7FC00000 : STD_LOGIC_VECTOR (31 downto 0) := "01111111110000000000000000000000";
    constant ap_const_lv32_BF800000 : STD_LOGIC_VECTOR (31 downto 0) := "10111111100000000000000000000000";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal erf_lut_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal erf_lut_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal erf_lut_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln35_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_reg_419_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_425_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_432_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_437_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_107_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_442 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_125_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_447 : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_447_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_447_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_447_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_447_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_447_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_reg_453 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_fu_304_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_458 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_fu_317_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_reg_464 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_reg_464_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln58_fu_324_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln58_reg_470 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln58_reg_470_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_134_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_reg_485 : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490 : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter16_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter17_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_reg_490_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal erf_lut_load_1_reg_496 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_113_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ratio_reg_501 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_117_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub2_reg_506 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_130_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_511 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln43_fu_328_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln43_1_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal erf_lut_ce1_local : STD_LOGIC;
    signal erf_lut_ce0_local : STD_LOGIC;
    signal bitcast_ln35_fu_155_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_159_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln35_fu_169_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln35_1_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_fu_191_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_210_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_214_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_202_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_228_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_232_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_246_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_238_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_fu_252_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_256_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_2_fu_264_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_224_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_268_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_272_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_278_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_7_fu_284_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_294_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_4_fu_312_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_fu_332_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln35_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln33_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_1_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln36_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln35_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln35_1_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln36_1_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_121_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_fu_387_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_fu_387_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal retval_fu_387_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_fu_387_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_fu_387_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_fu_387_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_fu_387_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_sitofp_32ns_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component activation_accelerator_sparsemux_9_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_lut_erf_erf_lut_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    erf_lut_U : component activation_accelerator_lut_erf_erf_lut_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => erf_lut_address0,
        ce0 => erf_lut_ce0_local,
        q0 => erf_lut_q0,
        address1 => erf_lut_address1,
        ce1 => erf_lut_ce1_local,
        q1 => erf_lut_q1);

    fadd_32ns_32ns_32_4_full_dsp_1_U167 : component activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_40800000,
        ce => ap_const_logic_1,
        dout => grp_fu_107_p2);

    fsub_32ns_32ns_32_4_full_dsp_1_U168 : component activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => idx_f_reg_447_pp0_iter11_reg,
        din1 => conv7_reg_485,
        ce => ap_const_logic_1,
        dout => grp_fu_113_p2);

    fsub_32ns_32ns_32_4_full_dsp_1_U169 : component activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => erf_lut_load_1_reg_496,
        din1 => erf_lut_load_reg_490,
        ce => ap_const_logic_1,
        dout => grp_fu_117_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U170 : component activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => erf_lut_load_reg_490_pp0_iter18_reg,
        din1 => mul_reg_511,
        ce => ap_const_logic_1,
        dout => grp_fu_121_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U171 : component activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_reg_442,
        din1 => ap_const_lv32_41FEFF0F,
        ce => ap_const_logic_1,
        dout => grp_fu_125_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U172 : component activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ratio_reg_501,
        din1 => sub2_reg_506,
        ce => ap_const_logic_1,
        dout => grp_fu_130_p2);

    sitofp_32ns_32_4_no_dsp_1_U173 : component activation_accelerator_sitofp_32ns_32_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => result_fu_317_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_134_p1);

    fcmp_32ns_32ns_1_2_no_dsp_1_U174 : component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_8,
        dout => grp_fu_137_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U175 : component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_C0800000,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_4,
        dout => grp_fu_143_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U176 : component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_40800000,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_149_p2);

    sparsemux_9_3_32_1_1_U177 : component activation_accelerator_sparsemux_9_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 32,
        CASE1 => "010",
        din1_WIDTH => 32,
        CASE2 => "001",
        din2_WIDTH => 32,
        CASE3 => "000",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_7FC00000,
        din1 => ap_const_lv32_BF800000,
        din2 => ap_const_lv32_3F800000,
        din3 => grp_fu_121_p2,
        def => retval_fu_387_p9,
        sel => retval_fu_387_p10,
        dout => retval_fu_387_p11);





    x_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            x_int_reg <= x;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                cmp_reg_425 <= grp_fu_137_p2;
                cmp_reg_425_pp0_iter10_reg <= cmp_reg_425_pp0_iter9_reg;
                cmp_reg_425_pp0_iter11_reg <= cmp_reg_425_pp0_iter10_reg;
                cmp_reg_425_pp0_iter12_reg <= cmp_reg_425_pp0_iter11_reg;
                cmp_reg_425_pp0_iter13_reg <= cmp_reg_425_pp0_iter12_reg;
                cmp_reg_425_pp0_iter14_reg <= cmp_reg_425_pp0_iter13_reg;
                cmp_reg_425_pp0_iter15_reg <= cmp_reg_425_pp0_iter14_reg;
                cmp_reg_425_pp0_iter16_reg <= cmp_reg_425_pp0_iter15_reg;
                cmp_reg_425_pp0_iter17_reg <= cmp_reg_425_pp0_iter16_reg;
                cmp_reg_425_pp0_iter18_reg <= cmp_reg_425_pp0_iter17_reg;
                cmp_reg_425_pp0_iter19_reg <= cmp_reg_425_pp0_iter18_reg;
                cmp_reg_425_pp0_iter20_reg <= cmp_reg_425_pp0_iter19_reg;
                cmp_reg_425_pp0_iter21_reg <= cmp_reg_425_pp0_iter20_reg;
                cmp_reg_425_pp0_iter2_reg <= cmp_reg_425;
                cmp_reg_425_pp0_iter3_reg <= cmp_reg_425_pp0_iter2_reg;
                cmp_reg_425_pp0_iter4_reg <= cmp_reg_425_pp0_iter3_reg;
                cmp_reg_425_pp0_iter5_reg <= cmp_reg_425_pp0_iter4_reg;
                cmp_reg_425_pp0_iter6_reg <= cmp_reg_425_pp0_iter5_reg;
                cmp_reg_425_pp0_iter7_reg <= cmp_reg_425_pp0_iter6_reg;
                cmp_reg_425_pp0_iter8_reg <= cmp_reg_425_pp0_iter7_reg;
                cmp_reg_425_pp0_iter9_reg <= cmp_reg_425_pp0_iter8_reg;
                conv7_reg_485 <= grp_fu_134_p1;
                erf_lut_load_1_reg_496 <= erf_lut_q0;
                erf_lut_load_reg_490 <= erf_lut_q1;
                erf_lut_load_reg_490_pp0_iter12_reg <= erf_lut_load_reg_490;
                erf_lut_load_reg_490_pp0_iter13_reg <= erf_lut_load_reg_490_pp0_iter12_reg;
                erf_lut_load_reg_490_pp0_iter14_reg <= erf_lut_load_reg_490_pp0_iter13_reg;
                erf_lut_load_reg_490_pp0_iter15_reg <= erf_lut_load_reg_490_pp0_iter14_reg;
                erf_lut_load_reg_490_pp0_iter16_reg <= erf_lut_load_reg_490_pp0_iter15_reg;
                erf_lut_load_reg_490_pp0_iter17_reg <= erf_lut_load_reg_490_pp0_iter16_reg;
                erf_lut_load_reg_490_pp0_iter18_reg <= erf_lut_load_reg_490_pp0_iter17_reg;
                idx_f_reg_447 <= grp_fu_125_p2;
                idx_f_reg_447_pp0_iter10_reg <= idx_f_reg_447_pp0_iter9_reg;
                idx_f_reg_447_pp0_iter11_reg <= idx_f_reg_447_pp0_iter10_reg;
                idx_f_reg_447_pp0_iter7_reg <= idx_f_reg_447;
                idx_f_reg_447_pp0_iter8_reg <= idx_f_reg_447_pp0_iter7_reg;
                idx_f_reg_447_pp0_iter9_reg <= idx_f_reg_447_pp0_iter8_reg;
                mul_reg_511 <= grp_fu_130_p2;
                or_ln35_reg_419 <= or_ln35_fu_185_p2;
                or_ln35_reg_419_pp0_iter10_reg <= or_ln35_reg_419_pp0_iter9_reg;
                or_ln35_reg_419_pp0_iter11_reg <= or_ln35_reg_419_pp0_iter10_reg;
                or_ln35_reg_419_pp0_iter12_reg <= or_ln35_reg_419_pp0_iter11_reg;
                or_ln35_reg_419_pp0_iter13_reg <= or_ln35_reg_419_pp0_iter12_reg;
                or_ln35_reg_419_pp0_iter14_reg <= or_ln35_reg_419_pp0_iter13_reg;
                or_ln35_reg_419_pp0_iter15_reg <= or_ln35_reg_419_pp0_iter14_reg;
                or_ln35_reg_419_pp0_iter16_reg <= or_ln35_reg_419_pp0_iter15_reg;
                or_ln35_reg_419_pp0_iter17_reg <= or_ln35_reg_419_pp0_iter16_reg;
                or_ln35_reg_419_pp0_iter18_reg <= or_ln35_reg_419_pp0_iter17_reg;
                or_ln35_reg_419_pp0_iter19_reg <= or_ln35_reg_419_pp0_iter18_reg;
                or_ln35_reg_419_pp0_iter1_reg <= or_ln35_reg_419;
                or_ln35_reg_419_pp0_iter20_reg <= or_ln35_reg_419_pp0_iter19_reg;
                or_ln35_reg_419_pp0_iter21_reg <= or_ln35_reg_419_pp0_iter20_reg;
                or_ln35_reg_419_pp0_iter2_reg <= or_ln35_reg_419_pp0_iter1_reg;
                or_ln35_reg_419_pp0_iter3_reg <= or_ln35_reg_419_pp0_iter2_reg;
                or_ln35_reg_419_pp0_iter4_reg <= or_ln35_reg_419_pp0_iter3_reg;
                or_ln35_reg_419_pp0_iter5_reg <= or_ln35_reg_419_pp0_iter4_reg;
                or_ln35_reg_419_pp0_iter6_reg <= or_ln35_reg_419_pp0_iter5_reg;
                or_ln35_reg_419_pp0_iter7_reg <= or_ln35_reg_419_pp0_iter6_reg;
                or_ln35_reg_419_pp0_iter8_reg <= or_ln35_reg_419_pp0_iter7_reg;
                or_ln35_reg_419_pp0_iter9_reg <= or_ln35_reg_419_pp0_iter8_reg;
                ratio_reg_501 <= grp_fu_113_p2;
                result_reg_464 <= result_fu_317_p3;
                result_reg_464_pp0_iter9_reg <= result_reg_464;
                sub2_reg_506 <= grp_fu_117_p2;
                sub_reg_442 <= grp_fu_107_p2;
                tmp_6_reg_432 <= grp_fu_143_p2;
                tmp_6_reg_432_pp0_iter10_reg <= tmp_6_reg_432_pp0_iter9_reg;
                tmp_6_reg_432_pp0_iter11_reg <= tmp_6_reg_432_pp0_iter10_reg;
                tmp_6_reg_432_pp0_iter12_reg <= tmp_6_reg_432_pp0_iter11_reg;
                tmp_6_reg_432_pp0_iter13_reg <= tmp_6_reg_432_pp0_iter12_reg;
                tmp_6_reg_432_pp0_iter14_reg <= tmp_6_reg_432_pp0_iter13_reg;
                tmp_6_reg_432_pp0_iter15_reg <= tmp_6_reg_432_pp0_iter14_reg;
                tmp_6_reg_432_pp0_iter16_reg <= tmp_6_reg_432_pp0_iter15_reg;
                tmp_6_reg_432_pp0_iter17_reg <= tmp_6_reg_432_pp0_iter16_reg;
                tmp_6_reg_432_pp0_iter18_reg <= tmp_6_reg_432_pp0_iter17_reg;
                tmp_6_reg_432_pp0_iter19_reg <= tmp_6_reg_432_pp0_iter18_reg;
                tmp_6_reg_432_pp0_iter20_reg <= tmp_6_reg_432_pp0_iter19_reg;
                tmp_6_reg_432_pp0_iter21_reg <= tmp_6_reg_432_pp0_iter20_reg;
                tmp_6_reg_432_pp0_iter2_reg <= tmp_6_reg_432;
                tmp_6_reg_432_pp0_iter3_reg <= tmp_6_reg_432_pp0_iter2_reg;
                tmp_6_reg_432_pp0_iter4_reg <= tmp_6_reg_432_pp0_iter3_reg;
                tmp_6_reg_432_pp0_iter5_reg <= tmp_6_reg_432_pp0_iter4_reg;
                tmp_6_reg_432_pp0_iter6_reg <= tmp_6_reg_432_pp0_iter5_reg;
                tmp_6_reg_432_pp0_iter7_reg <= tmp_6_reg_432_pp0_iter6_reg;
                tmp_6_reg_432_pp0_iter8_reg <= tmp_6_reg_432_pp0_iter7_reg;
                tmp_6_reg_432_pp0_iter9_reg <= tmp_6_reg_432_pp0_iter8_reg;
                tmp_8_reg_437 <= grp_fu_149_p2;
                tmp_8_reg_437_pp0_iter10_reg <= tmp_8_reg_437_pp0_iter9_reg;
                tmp_8_reg_437_pp0_iter11_reg <= tmp_8_reg_437_pp0_iter10_reg;
                tmp_8_reg_437_pp0_iter12_reg <= tmp_8_reg_437_pp0_iter11_reg;
                tmp_8_reg_437_pp0_iter13_reg <= tmp_8_reg_437_pp0_iter12_reg;
                tmp_8_reg_437_pp0_iter14_reg <= tmp_8_reg_437_pp0_iter13_reg;
                tmp_8_reg_437_pp0_iter15_reg <= tmp_8_reg_437_pp0_iter14_reg;
                tmp_8_reg_437_pp0_iter16_reg <= tmp_8_reg_437_pp0_iter15_reg;
                tmp_8_reg_437_pp0_iter17_reg <= tmp_8_reg_437_pp0_iter16_reg;
                tmp_8_reg_437_pp0_iter18_reg <= tmp_8_reg_437_pp0_iter17_reg;
                tmp_8_reg_437_pp0_iter19_reg <= tmp_8_reg_437_pp0_iter18_reg;
                tmp_8_reg_437_pp0_iter20_reg <= tmp_8_reg_437_pp0_iter19_reg;
                tmp_8_reg_437_pp0_iter21_reg <= tmp_8_reg_437_pp0_iter20_reg;
                tmp_8_reg_437_pp0_iter2_reg <= tmp_8_reg_437;
                tmp_8_reg_437_pp0_iter3_reg <= tmp_8_reg_437_pp0_iter2_reg;
                tmp_8_reg_437_pp0_iter4_reg <= tmp_8_reg_437_pp0_iter3_reg;
                tmp_8_reg_437_pp0_iter5_reg <= tmp_8_reg_437_pp0_iter4_reg;
                tmp_8_reg_437_pp0_iter6_reg <= tmp_8_reg_437_pp0_iter5_reg;
                tmp_8_reg_437_pp0_iter7_reg <= tmp_8_reg_437_pp0_iter6_reg;
                tmp_8_reg_437_pp0_iter8_reg <= tmp_8_reg_437_pp0_iter7_reg;
                tmp_8_reg_437_pp0_iter9_reg <= tmp_8_reg_437_pp0_iter8_reg;
                trunc_ln58_reg_470 <= trunc_ln58_fu_324_p1;
                trunc_ln58_reg_470_pp0_iter9_reg <= trunc_ln58_reg_470;
                val_reg_458 <= val_fu_304_p3;
                xs_sign_reg_453 <= data_fu_191_p1(31 downto 31);
            end if;
        end if;
    end process;
    add_ln317_fu_232_p2 <= std_logic_vector(unsigned(zext_ln317_fu_228_p1) + unsigned(ap_const_lv9_181));
    add_ln43_fu_332_p2 <= std_logic_vector(unsigned(trunc_ln58_reg_470_pp0_iter9_reg) + unsigned(ap_const_lv8_1));
    and_ln35_1_fu_355_p2 <= (xor_ln33_fu_350_p2 and and_ln35_fu_342_p2);
    and_ln35_fu_342_p2 <= (tmp_6_reg_432_pp0_iter21_reg and or_ln35_reg_419_pp0_iter21_reg);
    and_ln36_1_fu_372_p2 <= (xor_ln35_fu_366_p2 and and_ln36_fu_346_p2);
    and_ln36_fu_346_p2 <= (tmp_8_reg_437_pp0_iter21_reg and or_ln35_reg_419_pp0_iter21_reg);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= retval_fu_387_p11;
    bitcast_ln35_fu_155_p1 <= x_int_reg;
    data_fu_191_p1 <= idx_f_reg_447;
    erf_lut_address0 <= zext_ln43_1_fu_337_p1(8 - 1 downto 0);
    erf_lut_address1 <= zext_ln43_fu_328_p1(8 - 1 downto 0);

    erf_lut_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            erf_lut_ce0_local <= ap_const_logic_1;
        else 
            erf_lut_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    erf_lut_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            erf_lut_ce1_local <= ap_const_logic_1;
        else 
            erf_lut_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln35_1_fu_179_p2 <= "1" when (trunc_ln35_fu_169_p1 = ap_const_lv23_0) else "0";
    icmp_ln35_fu_173_p2 <= "0" when (tmp_5_fu_159_p4 = ap_const_lv8_FF) else "1";
    lshr_ln18_fu_272_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_224_p1),to_integer(unsigned('0' & zext_ln18_fu_268_p1(31-1 downto 0)))));
    mantissa_fu_214_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_210_p1) & ap_const_lv1_0);
    or_ln35_1_fu_361_p2 <= (cmp_reg_425_pp0_iter21_reg or and_ln35_fu_342_p2);
    or_ln35_fu_185_p2 <= (icmp_ln35_fu_173_p2 or icmp_ln35_1_fu_179_p2);
    result_4_fu_312_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_reg_458));
    result_fu_317_p3 <= 
        result_4_fu_312_p2 when (xs_sign_reg_453(0) = '1') else 
        val_reg_458;
    retval_fu_387_p10 <= ((cmp_reg_425_pp0_iter21_reg & and_ln35_1_fu_355_p2) & and_ln36_1_fu_372_p2);
    retval_fu_387_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln18_fu_256_p3 <= 
        sext_ln18_fu_252_p1 when (tmp_fu_238_p3(0) = '1') else 
        add_ln317_fu_232_p2;
        sext_ln18_2_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_256_p3),32));

        sext_ln18_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_246_p2),9));

    shl_ln18_fu_278_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_224_p1),to_integer(unsigned('0' & zext_ln18_fu_268_p1(31-1 downto 0)))));
    sub_ln18_fu_246_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_202_p3));
    tmp_5_fu_159_p4 <= bitcast_ln35_fu_155_p1(30 downto 23);
    tmp_7_fu_284_p4 <= lshr_ln18_fu_272_p2(55 downto 24);
    tmp_9_fu_294_p4 <= shl_ln18_fu_278_p2(55 downto 24);
    tmp_fu_238_p3 <= add_ln317_fu_232_p2(8 downto 8);
    trunc_ln342_fu_210_p1 <= data_fu_191_p1(23 - 1 downto 0);
    trunc_ln35_fu_169_p1 <= bitcast_ln35_fu_155_p1(23 - 1 downto 0);
    trunc_ln58_fu_324_p1 <= result_fu_317_p3(8 - 1 downto 0);
    val_fu_304_p3 <= 
        tmp_7_fu_284_p4 when (tmp_fu_238_p3(0) = '1') else 
        tmp_9_fu_294_p4;
    xor_ln33_fu_350_p2 <= (cmp_reg_425_pp0_iter21_reg xor ap_const_lv1_1);
    xor_ln35_fu_366_p2 <= (or_ln35_1_fu_361_p2 xor ap_const_lv1_1);
    xs_exp_fu_202_p3 <= data_fu_191_p1(30 downto 23);
    zext_ln15_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_214_p4),79));
    zext_ln18_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_2_fu_264_p1),79));
    zext_ln317_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_202_p3),9));
    zext_ln43_1_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_fu_332_p2),64));
    zext_ln43_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_reg_464_pp0_iter9_reg),64));
end behav;
