-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_657_46 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_WREADY : IN STD_LOGIC;
    m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RVALID : IN STD_LOGIC;
    m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem2_0_RLAST : IN STD_LOGIC;
    m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BVALID : IN STD_LOGIC;
    m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln657 : IN STD_LOGIC_VECTOR (58 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0 : OUT STD_LOGIC;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0 : OUT STD_LOGIC;
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0 : OUT STD_LOGIC;
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0 : OUT STD_LOGIC;
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0 : OUT STD_LOGIC;
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0 : OUT STD_LOGIC;
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0 : OUT STD_LOGIC;
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_657_46 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_C00 : STD_LOGIC_VECTOR (11 downto 0) := "110000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln657_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem2_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal e_reg_480 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_1_reg_485 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_2_reg_490 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_3_reg_495 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_4_reg_500 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_5_reg_505 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_6_reg_510 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_7_reg_515 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_8_reg_520 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_9_reg_525 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_10_reg_530 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_11_reg_535 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_12_reg_540 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_13_reg_545 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_14_reg_550 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_15_reg_555 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln657_fu_332_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal p_fu_82 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln657_fu_326_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_p_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local : STD_LOGIC;
    signal activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local : STD_LOGIC;
    signal p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local : STD_LOGIC;
    signal p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local : STD_LOGIC;
    signal p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local : STD_LOGIC;
    signal p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local : STD_LOGIC;
    signal p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local : STD_LOGIC;
    signal p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component activation_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component activation_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    p_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln657_fu_320_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    p_fu_82 <= add_ln657_fu_326_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    p_fu_82 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                e_10_reg_530 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_q0;
                e_11_reg_535 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_q0;
                e_12_reg_540 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_q0;
                e_13_reg_545 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_q0;
                e_14_reg_550 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_q0;
                e_15_reg_555 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_q0;
                e_1_reg_485 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_q0;
                e_2_reg_490 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_q0;
                e_3_reg_495 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_q0;
                e_4_reg_500 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_q0;
                e_5_reg_505 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_q0;
                e_6_reg_510 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_q0;
                e_7_reg_515 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_q0;
                e_8_reg_520 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_q0;
                e_9_reg_525 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_q0;
                e_reg_480 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local;

    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local <= ap_const_logic_1;
        else 
            activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln657_fu_326_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_p_1) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem2_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem2_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem2_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln657_fu_320_p2)
    begin
        if (((icmp_ln657_fu_320_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_p_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, p_fu_82, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_p_1 <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_p_1 <= p_fu_82;
        end if; 
    end process;


    gmem2_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem2_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem2_blk_n_W <= m_axi_gmem2_0_WREADY;
        else 
            gmem2_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln657_fu_320_p2 <= "1" when (ap_sig_allocacmp_p_1 = ap_const_lv12_C00) else "0";
    m_axi_gmem2_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_ARID <= ap_const_lv1_0;
    m_axi_gmem2_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem2_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_AWID <= ap_const_lv1_0;
    m_axi_gmem2_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_0_BREADY <= ap_const_logic_0;
    m_axi_gmem2_0_RREADY <= ap_const_logic_0;
    m_axi_gmem2_0_WDATA <= (((((((((((((((e_15_reg_555 & e_14_reg_550) & e_13_reg_545) & e_12_reg_540) & e_11_reg_535) & e_10_reg_530) & e_9_reg_525) & e_8_reg_520) & e_7_reg_515) & e_6_reg_510) & e_5_reg_505) & e_4_reg_500) & e_3_reg_495) & e_2_reg_490) & e_1_reg_485) & e_reg_480);
    m_axi_gmem2_0_WID <= ap_const_lv1_0;
    m_axi_gmem2_0_WLAST <= ap_const_logic_0;
    m_axi_gmem2_0_WSTRB <= ap_const_lv32_FFFFFFFF;
    m_axi_gmem2_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem2_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_gmem2_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_address0 <= zext_ln657_fu_332_p1(12 - 1 downto 0);
    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local;

    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln657_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_p_1),64));
end behav;
