-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity activation_accelerator_lut_exp is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of activation_accelerator_lut_exp is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_41800000 : STD_LOGIC_VECTOR (31 downto 0) := "01000001100000000000000000000000";
    constant ap_const_lv32_41FF7D5F : STD_LOGIC_VECTOR (31 downto 0) := "01000001111111110111110101011111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_C1800000 : STD_LOGIC_VECTOR (31 downto 0) := "11000001100000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_7FC00000 : STD_LOGIC_VECTOR (31 downto 0) := "01111111110000000000000000000000";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";

attribute shreg_extract : string;
    signal exp_lut_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal exp_lut_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal exp_lut_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln19_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_417_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_reg_423_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_430_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_435_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_105_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_440 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_123_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_445 : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_445_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_445_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_445_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_445_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_f_reg_445_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_reg_451 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_fu_302_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_456 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_fu_315_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_reg_462_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln58_fu_322_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln58_reg_468 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln58_reg_468_pp0_iter9_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_132_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv7_reg_483 : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488 : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter16_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter17_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_reg_488_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_lut_load_1_reg_494 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_111_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ratio_reg_499 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_115_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub1_reg_504 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_128_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_509 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln28_fu_326_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln28_1_fu_335_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exp_lut_ce1_local : STD_LOGIC;
    signal exp_lut_ce0_local : STD_LOGIC;
    signal bitcast_ln19_fu_153_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_157_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln19_fu_167_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln19_1_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln19_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_fu_189_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_208_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_212_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_200_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_226_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_230_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_244_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_fu_250_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_254_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_1_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_222_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_266_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_270_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_276_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_3_fu_282_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_292_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_2_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln28_fu_330_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal and_ln20_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln19_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_1_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln19_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln19_1_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_119_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_fu_385_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_fu_385_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_105_ce : STD_LOGIC;
    signal grp_fu_111_ce : STD_LOGIC;
    signal grp_fu_115_ce : STD_LOGIC;
    signal grp_fu_119_ce : STD_LOGIC;
    signal grp_fu_123_ce : STD_LOGIC;
    signal grp_fu_128_ce : STD_LOGIC;
    signal grp_fu_132_ce : STD_LOGIC;
    signal grp_fu_135_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal grp_fu_141_ce : STD_LOGIC;
    signal grp_fu_147_ce : STD_LOGIC;
    signal retval_fu_385_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_fu_385_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_fu_385_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_fu_385_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_fu_385_p7 : STD_LOGIC_VECTOR (2 downto 0);

    component activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_sitofp_32ns_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component activation_accelerator_sparsemux_9_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_lut_exp_exp_lut_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    exp_lut_U : component activation_accelerator_lut_exp_exp_lut_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_lut_address0,
        ce0 => exp_lut_ce0_local,
        q0 => exp_lut_q0,
        address1 => exp_lut_address1,
        ce1 => exp_lut_ce1_local,
        q1 => exp_lut_q1);

    fadd_32ns_32ns_32_4_full_dsp_1_U639 : component activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_41800000,
        ce => grp_fu_105_ce,
        dout => grp_fu_105_p2);

    fsub_32ns_32ns_32_4_full_dsp_1_U640 : component activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => idx_f_reg_445_pp0_iter11_reg,
        din1 => conv7_reg_483,
        ce => grp_fu_111_ce,
        dout => grp_fu_111_p2);

    fsub_32ns_32ns_32_4_full_dsp_1_U641 : component activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => exp_lut_load_1_reg_494,
        din1 => exp_lut_load_reg_488,
        ce => grp_fu_115_ce,
        dout => grp_fu_115_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U642 : component activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => exp_lut_load_reg_488_pp0_iter18_reg,
        din1 => mul_reg_509,
        ce => grp_fu_119_ce,
        dout => grp_fu_119_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U643 : component activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_reg_440,
        din1 => ap_const_lv32_41FF7D5F,
        ce => grp_fu_123_ce,
        dout => grp_fu_123_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U644 : component activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ratio_reg_499,
        din1 => sub1_reg_504,
        ce => grp_fu_128_ce,
        dout => grp_fu_128_p2);

    sitofp_32ns_32_4_no_dsp_1_U645 : component activation_accelerator_sitofp_32ns_32_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => result_fu_315_p3,
        ce => grp_fu_132_ce,
        dout => grp_fu_132_p1);

    fcmp_32ns_32ns_1_2_no_dsp_1_U646 : component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_0,
        ce => grp_fu_135_ce,
        opcode => ap_const_lv5_8,
        dout => grp_fu_135_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U647 : component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_C1800000,
        ce => grp_fu_141_ce,
        opcode => ap_const_lv5_5,
        dout => grp_fu_141_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U648 : component activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_int_reg,
        din1 => ap_const_lv32_0,
        ce => grp_fu_147_ce,
        opcode => ap_const_lv5_3,
        dout => grp_fu_147_p2);

    sparsemux_9_3_32_1_1_U649 : component activation_accelerator_sparsemux_9_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 32,
        CASE1 => "010",
        din1_WIDTH => 32,
        CASE2 => "001",
        din2_WIDTH => 32,
        CASE3 => "000",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_7FC00000,
        din1 => grp_fu_119_p2,
        din2 => ap_const_lv32_0,
        din3 => ap_const_lv32_3F800000,
        def => retval_fu_385_p9,
        sel => retval_fu_385_p10,
        dout => retval_fu_385_p11);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= retval_fu_385_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                cmp_reg_423 <= grp_fu_135_p2;
                cmp_reg_423_pp0_iter10_reg <= cmp_reg_423_pp0_iter9_reg;
                cmp_reg_423_pp0_iter11_reg <= cmp_reg_423_pp0_iter10_reg;
                cmp_reg_423_pp0_iter12_reg <= cmp_reg_423_pp0_iter11_reg;
                cmp_reg_423_pp0_iter13_reg <= cmp_reg_423_pp0_iter12_reg;
                cmp_reg_423_pp0_iter14_reg <= cmp_reg_423_pp0_iter13_reg;
                cmp_reg_423_pp0_iter15_reg <= cmp_reg_423_pp0_iter14_reg;
                cmp_reg_423_pp0_iter16_reg <= cmp_reg_423_pp0_iter15_reg;
                cmp_reg_423_pp0_iter17_reg <= cmp_reg_423_pp0_iter16_reg;
                cmp_reg_423_pp0_iter18_reg <= cmp_reg_423_pp0_iter17_reg;
                cmp_reg_423_pp0_iter19_reg <= cmp_reg_423_pp0_iter18_reg;
                cmp_reg_423_pp0_iter20_reg <= cmp_reg_423_pp0_iter19_reg;
                cmp_reg_423_pp0_iter21_reg <= cmp_reg_423_pp0_iter20_reg;
                cmp_reg_423_pp0_iter2_reg <= cmp_reg_423;
                cmp_reg_423_pp0_iter3_reg <= cmp_reg_423_pp0_iter2_reg;
                cmp_reg_423_pp0_iter4_reg <= cmp_reg_423_pp0_iter3_reg;
                cmp_reg_423_pp0_iter5_reg <= cmp_reg_423_pp0_iter4_reg;
                cmp_reg_423_pp0_iter6_reg <= cmp_reg_423_pp0_iter5_reg;
                cmp_reg_423_pp0_iter7_reg <= cmp_reg_423_pp0_iter6_reg;
                cmp_reg_423_pp0_iter8_reg <= cmp_reg_423_pp0_iter7_reg;
                cmp_reg_423_pp0_iter9_reg <= cmp_reg_423_pp0_iter8_reg;
                conv7_reg_483 <= grp_fu_132_p1;
                exp_lut_load_1_reg_494 <= exp_lut_q0;
                exp_lut_load_reg_488 <= exp_lut_q1;
                exp_lut_load_reg_488_pp0_iter12_reg <= exp_lut_load_reg_488;
                exp_lut_load_reg_488_pp0_iter13_reg <= exp_lut_load_reg_488_pp0_iter12_reg;
                exp_lut_load_reg_488_pp0_iter14_reg <= exp_lut_load_reg_488_pp0_iter13_reg;
                exp_lut_load_reg_488_pp0_iter15_reg <= exp_lut_load_reg_488_pp0_iter14_reg;
                exp_lut_load_reg_488_pp0_iter16_reg <= exp_lut_load_reg_488_pp0_iter15_reg;
                exp_lut_load_reg_488_pp0_iter17_reg <= exp_lut_load_reg_488_pp0_iter16_reg;
                exp_lut_load_reg_488_pp0_iter18_reg <= exp_lut_load_reg_488_pp0_iter17_reg;
                idx_f_reg_445 <= grp_fu_123_p2;
                idx_f_reg_445_pp0_iter10_reg <= idx_f_reg_445_pp0_iter9_reg;
                idx_f_reg_445_pp0_iter11_reg <= idx_f_reg_445_pp0_iter10_reg;
                idx_f_reg_445_pp0_iter7_reg <= idx_f_reg_445;
                idx_f_reg_445_pp0_iter8_reg <= idx_f_reg_445_pp0_iter7_reg;
                idx_f_reg_445_pp0_iter9_reg <= idx_f_reg_445_pp0_iter8_reg;
                mul_reg_509 <= grp_fu_128_p2;
                or_ln19_reg_417 <= or_ln19_fu_183_p2;
                or_ln19_reg_417_pp0_iter10_reg <= or_ln19_reg_417_pp0_iter9_reg;
                or_ln19_reg_417_pp0_iter11_reg <= or_ln19_reg_417_pp0_iter10_reg;
                or_ln19_reg_417_pp0_iter12_reg <= or_ln19_reg_417_pp0_iter11_reg;
                or_ln19_reg_417_pp0_iter13_reg <= or_ln19_reg_417_pp0_iter12_reg;
                or_ln19_reg_417_pp0_iter14_reg <= or_ln19_reg_417_pp0_iter13_reg;
                or_ln19_reg_417_pp0_iter15_reg <= or_ln19_reg_417_pp0_iter14_reg;
                or_ln19_reg_417_pp0_iter16_reg <= or_ln19_reg_417_pp0_iter15_reg;
                or_ln19_reg_417_pp0_iter17_reg <= or_ln19_reg_417_pp0_iter16_reg;
                or_ln19_reg_417_pp0_iter18_reg <= or_ln19_reg_417_pp0_iter17_reg;
                or_ln19_reg_417_pp0_iter19_reg <= or_ln19_reg_417_pp0_iter18_reg;
                or_ln19_reg_417_pp0_iter1_reg <= or_ln19_reg_417;
                or_ln19_reg_417_pp0_iter20_reg <= or_ln19_reg_417_pp0_iter19_reg;
                or_ln19_reg_417_pp0_iter21_reg <= or_ln19_reg_417_pp0_iter20_reg;
                or_ln19_reg_417_pp0_iter2_reg <= or_ln19_reg_417_pp0_iter1_reg;
                or_ln19_reg_417_pp0_iter3_reg <= or_ln19_reg_417_pp0_iter2_reg;
                or_ln19_reg_417_pp0_iter4_reg <= or_ln19_reg_417_pp0_iter3_reg;
                or_ln19_reg_417_pp0_iter5_reg <= or_ln19_reg_417_pp0_iter4_reg;
                or_ln19_reg_417_pp0_iter6_reg <= or_ln19_reg_417_pp0_iter5_reg;
                or_ln19_reg_417_pp0_iter7_reg <= or_ln19_reg_417_pp0_iter6_reg;
                or_ln19_reg_417_pp0_iter8_reg <= or_ln19_reg_417_pp0_iter7_reg;
                or_ln19_reg_417_pp0_iter9_reg <= or_ln19_reg_417_pp0_iter8_reg;
                ratio_reg_499 <= grp_fu_111_p2;
                result_reg_462 <= result_fu_315_p3;
                result_reg_462_pp0_iter9_reg <= result_reg_462;
                sub1_reg_504 <= grp_fu_115_p2;
                sub_reg_440 <= grp_fu_105_p2;
                tmp_2_reg_430 <= grp_fu_141_p2;
                tmp_2_reg_430_pp0_iter10_reg <= tmp_2_reg_430_pp0_iter9_reg;
                tmp_2_reg_430_pp0_iter11_reg <= tmp_2_reg_430_pp0_iter10_reg;
                tmp_2_reg_430_pp0_iter12_reg <= tmp_2_reg_430_pp0_iter11_reg;
                tmp_2_reg_430_pp0_iter13_reg <= tmp_2_reg_430_pp0_iter12_reg;
                tmp_2_reg_430_pp0_iter14_reg <= tmp_2_reg_430_pp0_iter13_reg;
                tmp_2_reg_430_pp0_iter15_reg <= tmp_2_reg_430_pp0_iter14_reg;
                tmp_2_reg_430_pp0_iter16_reg <= tmp_2_reg_430_pp0_iter15_reg;
                tmp_2_reg_430_pp0_iter17_reg <= tmp_2_reg_430_pp0_iter16_reg;
                tmp_2_reg_430_pp0_iter18_reg <= tmp_2_reg_430_pp0_iter17_reg;
                tmp_2_reg_430_pp0_iter19_reg <= tmp_2_reg_430_pp0_iter18_reg;
                tmp_2_reg_430_pp0_iter20_reg <= tmp_2_reg_430_pp0_iter19_reg;
                tmp_2_reg_430_pp0_iter21_reg <= tmp_2_reg_430_pp0_iter20_reg;
                tmp_2_reg_430_pp0_iter2_reg <= tmp_2_reg_430;
                tmp_2_reg_430_pp0_iter3_reg <= tmp_2_reg_430_pp0_iter2_reg;
                tmp_2_reg_430_pp0_iter4_reg <= tmp_2_reg_430_pp0_iter3_reg;
                tmp_2_reg_430_pp0_iter5_reg <= tmp_2_reg_430_pp0_iter4_reg;
                tmp_2_reg_430_pp0_iter6_reg <= tmp_2_reg_430_pp0_iter5_reg;
                tmp_2_reg_430_pp0_iter7_reg <= tmp_2_reg_430_pp0_iter6_reg;
                tmp_2_reg_430_pp0_iter8_reg <= tmp_2_reg_430_pp0_iter7_reg;
                tmp_2_reg_430_pp0_iter9_reg <= tmp_2_reg_430_pp0_iter8_reg;
                tmp_4_reg_435 <= grp_fu_147_p2;
                tmp_4_reg_435_pp0_iter10_reg <= tmp_4_reg_435_pp0_iter9_reg;
                tmp_4_reg_435_pp0_iter11_reg <= tmp_4_reg_435_pp0_iter10_reg;
                tmp_4_reg_435_pp0_iter12_reg <= tmp_4_reg_435_pp0_iter11_reg;
                tmp_4_reg_435_pp0_iter13_reg <= tmp_4_reg_435_pp0_iter12_reg;
                tmp_4_reg_435_pp0_iter14_reg <= tmp_4_reg_435_pp0_iter13_reg;
                tmp_4_reg_435_pp0_iter15_reg <= tmp_4_reg_435_pp0_iter14_reg;
                tmp_4_reg_435_pp0_iter16_reg <= tmp_4_reg_435_pp0_iter15_reg;
                tmp_4_reg_435_pp0_iter17_reg <= tmp_4_reg_435_pp0_iter16_reg;
                tmp_4_reg_435_pp0_iter18_reg <= tmp_4_reg_435_pp0_iter17_reg;
                tmp_4_reg_435_pp0_iter19_reg <= tmp_4_reg_435_pp0_iter18_reg;
                tmp_4_reg_435_pp0_iter20_reg <= tmp_4_reg_435_pp0_iter19_reg;
                tmp_4_reg_435_pp0_iter21_reg <= tmp_4_reg_435_pp0_iter20_reg;
                tmp_4_reg_435_pp0_iter2_reg <= tmp_4_reg_435;
                tmp_4_reg_435_pp0_iter3_reg <= tmp_4_reg_435_pp0_iter2_reg;
                tmp_4_reg_435_pp0_iter4_reg <= tmp_4_reg_435_pp0_iter3_reg;
                tmp_4_reg_435_pp0_iter5_reg <= tmp_4_reg_435_pp0_iter4_reg;
                tmp_4_reg_435_pp0_iter6_reg <= tmp_4_reg_435_pp0_iter5_reg;
                tmp_4_reg_435_pp0_iter7_reg <= tmp_4_reg_435_pp0_iter6_reg;
                tmp_4_reg_435_pp0_iter8_reg <= tmp_4_reg_435_pp0_iter7_reg;
                tmp_4_reg_435_pp0_iter9_reg <= tmp_4_reg_435_pp0_iter8_reg;
                trunc_ln58_reg_468 <= trunc_ln58_fu_322_p1;
                trunc_ln58_reg_468_pp0_iter9_reg <= trunc_ln58_reg_468;
                val_reg_456 <= val_fu_302_p3;
                xs_sign_reg_451 <= data_fu_189_p1(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    add_ln28_fu_330_p2 <= std_logic_vector(unsigned(trunc_ln58_reg_468_pp0_iter9_reg) + unsigned(ap_const_lv9_1));
    add_ln317_fu_230_p2 <= std_logic_vector(unsigned(zext_ln317_fu_226_p1) + unsigned(ap_const_lv9_181));
    and_ln19_1_fu_370_p2 <= (xor_ln19_fu_365_p2 and and_ln19_fu_340_p2);
    and_ln19_fu_340_p2 <= (tmp_2_reg_430_pp0_iter21_reg and or_ln19_reg_417_pp0_iter21_reg);
    and_ln20_fu_344_p2 <= (tmp_4_reg_435_pp0_iter21_reg and or_ln19_reg_417_pp0_iter21_reg);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(retval_fu_385_p11, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= retval_fu_385_p11;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bitcast_ln19_fu_153_p1 <= x_int_reg;
    data_fu_189_p1 <= idx_f_reg_445;
    exp_lut_address0 <= zext_ln28_1_fu_335_p1(9 - 1 downto 0);
    exp_lut_address1 <= zext_ln28_fu_326_p1(9 - 1 downto 0);

    exp_lut_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_lut_ce0_local <= ap_const_logic_1;
        else 
            exp_lut_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_lut_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_lut_ce1_local <= ap_const_logic_1;
        else 
            exp_lut_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_105_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_105_ce <= ap_const_logic_1;
        else 
            grp_fu_105_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_111_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_111_ce <= ap_const_logic_1;
        else 
            grp_fu_111_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_115_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_115_ce <= ap_const_logic_1;
        else 
            grp_fu_115_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_119_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_119_ce <= ap_const_logic_1;
        else 
            grp_fu_119_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_123_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_123_ce <= ap_const_logic_1;
        else 
            grp_fu_123_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_128_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_128_ce <= ap_const_logic_1;
        else 
            grp_fu_128_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_132_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_132_ce <= ap_const_logic_1;
        else 
            grp_fu_132_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_135_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_135_ce <= ap_const_logic_1;
        else 
            grp_fu_135_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_141_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_141_ce <= ap_const_logic_1;
        else 
            grp_fu_141_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_147_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_147_ce <= ap_const_logic_1;
        else 
            grp_fu_147_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln19_1_fu_177_p2 <= "1" when (trunc_ln19_fu_167_p1 = ap_const_lv23_0) else "0";
    icmp_ln19_fu_171_p2 <= "0" when (tmp_1_fu_157_p4 = ap_const_lv8_FF) else "1";
    lshr_ln18_fu_270_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_222_p1),to_integer(unsigned('0' & zext_ln18_fu_266_p1(31-1 downto 0)))));
    mantissa_fu_212_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_208_p1) & ap_const_lv1_0);
    or_ln19_fu_183_p2 <= (icmp_ln19_fu_171_p2 or icmp_ln19_1_fu_177_p2);
    or_ln20_1_fu_353_p2 <= (or_ln20_fu_348_p2 or and_ln19_fu_340_p2);
    or_ln20_fu_348_p2 <= (cmp_reg_423_pp0_iter21_reg or and_ln20_fu_344_p2);
    result_2_fu_310_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_reg_456));
    result_fu_315_p3 <= 
        result_2_fu_310_p2 when (xs_sign_reg_451(0) = '1') else 
        val_reg_456;
    retval_fu_385_p10 <= ((cmp_reg_423_pp0_iter21_reg & xor_ln20_fu_359_p2) & and_ln19_1_fu_370_p2);
    retval_fu_385_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln18_fu_254_p3 <= 
        sext_ln18_fu_250_p1 when (tmp_fu_236_p3(0) = '1') else 
        add_ln317_fu_230_p2;
        sext_ln18_1_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_254_p3),32));

        sext_ln18_fu_250_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_244_p2),9));

    shl_ln18_fu_276_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_222_p1),to_integer(unsigned('0' & zext_ln18_fu_266_p1(31-1 downto 0)))));
    sub_ln18_fu_244_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_200_p3));
    tmp_1_fu_157_p4 <= bitcast_ln19_fu_153_p1(30 downto 23);
    tmp_3_fu_282_p4 <= lshr_ln18_fu_270_p2(55 downto 24);
    tmp_5_fu_292_p4 <= shl_ln18_fu_276_p2(55 downto 24);
    tmp_fu_236_p3 <= add_ln317_fu_230_p2(8 downto 8);
    trunc_ln19_fu_167_p1 <= bitcast_ln19_fu_153_p1(23 - 1 downto 0);
    trunc_ln342_fu_208_p1 <= data_fu_189_p1(23 - 1 downto 0);
    trunc_ln58_fu_322_p1 <= result_fu_315_p3(9 - 1 downto 0);
    val_fu_302_p3 <= 
        tmp_3_fu_282_p4 when (tmp_fu_236_p3(0) = '1') else 
        tmp_5_fu_292_p4;
    xor_ln19_fu_365_p2 <= (cmp_reg_423_pp0_iter21_reg xor ap_const_lv1_1);
    xor_ln20_fu_359_p2 <= (or_ln20_1_fu_353_p2 xor ap_const_lv1_1);
    xs_exp_fu_200_p3 <= data_fu_189_p1(30 downto 23);
    zext_ln15_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_212_p4),79));
    zext_ln18_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_262_p1),79));
    zext_ln28_1_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln28_fu_330_p2),64));
    zext_ln28_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_reg_462_pp0_iter9_reg),64));
    zext_ln317_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_200_p3),9));
end behav;
