// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_103_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        sext_ln103,
        sext_ln103_1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_d1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_address1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_d1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_address1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_d1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_address1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_d1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_address1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_d1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_address1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_d1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_address1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_d1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_address1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [255:0] m_axi_gmem0_0_WDATA;
output  [31:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [255:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [8:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [255:0] m_axi_gmem1_0_WDATA;
output  [31:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [255:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [8:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [58:0] sext_ln103;
input  [58:0] sext_ln103_1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_d0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_d0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_d0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_d0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_d0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_d0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_d0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_d1;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_address1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_d1;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_address1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_d1;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_address1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_d1;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_address1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_d1;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_address1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_d1;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_address1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_d1;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_address1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_d1;

reg ap_idle;
reg m_axi_gmem0_0_RREADY;
reg m_axi_gmem1_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
wire   [0:0] icmp_ln103_fu_678_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0_grp2;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [11:0] p_2_reg_1007;
reg    ap_block_pp0_stage0_11001;
reg   [11:0] p_2_reg_1007_pp0_iter1_reg;
wire   [15:0] e0_fu_707_p1;
reg   [15:0] e0_reg_1016;
wire   [15:0] e1_fu_711_p1;
reg   [15:0] e1_reg_1021;
reg   [15:0] e0_1_reg_1026;
reg   [15:0] e1_1_reg_1031;
reg   [15:0] e0_2_reg_1036;
reg   [15:0] e1_2_reg_1041;
reg   [15:0] e0_3_reg_1046;
reg   [15:0] e1_3_reg_1051;
reg   [15:0] e0_4_reg_1056;
reg   [15:0] e1_4_reg_1061;
reg   [15:0] e0_5_reg_1066;
reg   [15:0] e1_5_reg_1071;
reg   [15:0] e0_6_reg_1076;
reg   [15:0] e1_6_reg_1081;
reg   [15:0] e0_7_reg_1086;
reg   [15:0] e1_7_reg_1091;
reg   [15:0] e0_8_reg_1096;
reg   [15:0] e1_8_reg_1101;
reg   [15:0] e0_9_reg_1106;
reg   [15:0] e1_9_reg_1111;
reg   [15:0] e0_10_reg_1116;
reg   [15:0] e1_10_reg_1121;
reg   [15:0] e0_11_reg_1126;
reg   [15:0] e1_11_reg_1131;
reg   [15:0] e0_12_reg_1136;
reg   [15:0] e1_12_reg_1141;
reg   [15:0] e0_13_reg_1146;
reg   [15:0] e1_13_reg_1151;
reg   [15:0] e0_14_reg_1156;
reg   [15:0] e1_14_reg_1161;
reg   [15:0] e0_15_reg_1166;
reg   [15:0] e1_15_reg_1171;
wire   [63:0] zext_ln103_fu_955_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [11:0] p_fu_156;
wire   [11:0] add_ln103_fu_684_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_p_2;
wire    ap_block_pp0_stage0;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 p_fu_156 = 12'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

activation_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln103_fu_678_p2 == 1'd0))) begin
            p_fu_156 <= add_ln103_fu_684_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_156 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        p_2_reg_1007 <= ap_sig_allocacmp_p_2;
        p_2_reg_1007_pp0_iter1_reg <= p_2_reg_1007;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))) begin
        e0_10_reg_1116 <= {{m_axi_gmem0_0_RDATA[175:160]}};
        e0_11_reg_1126 <= {{m_axi_gmem0_0_RDATA[191:176]}};
        e0_12_reg_1136 <= {{m_axi_gmem0_0_RDATA[207:192]}};
        e0_13_reg_1146 <= {{m_axi_gmem0_0_RDATA[223:208]}};
        e0_14_reg_1156 <= {{m_axi_gmem0_0_RDATA[239:224]}};
        e0_15_reg_1166 <= {{m_axi_gmem0_0_RDATA[255:240]}};
        e0_1_reg_1026 <= {{m_axi_gmem0_0_RDATA[31:16]}};
        e0_2_reg_1036 <= {{m_axi_gmem0_0_RDATA[47:32]}};
        e0_3_reg_1046 <= {{m_axi_gmem0_0_RDATA[63:48]}};
        e0_4_reg_1056 <= {{m_axi_gmem0_0_RDATA[79:64]}};
        e0_5_reg_1066 <= {{m_axi_gmem0_0_RDATA[95:80]}};
        e0_6_reg_1076 <= {{m_axi_gmem0_0_RDATA[111:96]}};
        e0_7_reg_1086 <= {{m_axi_gmem0_0_RDATA[127:112]}};
        e0_8_reg_1096 <= {{m_axi_gmem0_0_RDATA[143:128]}};
        e0_9_reg_1106 <= {{m_axi_gmem0_0_RDATA[159:144]}};
        e0_reg_1016 <= e0_fu_707_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg))) begin
        e1_10_reg_1121 <= {{m_axi_gmem1_0_RDATA[175:160]}};
        e1_11_reg_1131 <= {{m_axi_gmem1_0_RDATA[191:176]}};
        e1_12_reg_1141 <= {{m_axi_gmem1_0_RDATA[207:192]}};
        e1_13_reg_1151 <= {{m_axi_gmem1_0_RDATA[223:208]}};
        e1_14_reg_1161 <= {{m_axi_gmem1_0_RDATA[239:224]}};
        e1_15_reg_1171 <= {{m_axi_gmem1_0_RDATA[255:240]}};
        e1_1_reg_1031 <= {{m_axi_gmem1_0_RDATA[31:16]}};
        e1_2_reg_1041 <= {{m_axi_gmem1_0_RDATA[47:32]}};
        e1_3_reg_1051 <= {{m_axi_gmem1_0_RDATA[63:48]}};
        e1_4_reg_1061 <= {{m_axi_gmem1_0_RDATA[79:64]}};
        e1_5_reg_1071 <= {{m_axi_gmem1_0_RDATA[95:80]}};
        e1_6_reg_1081 <= {{m_axi_gmem1_0_RDATA[111:96]}};
        e1_7_reg_1091 <= {{m_axi_gmem1_0_RDATA[127:112]}};
        e1_8_reg_1101 <= {{m_axi_gmem1_0_RDATA[143:128]}};
        e1_9_reg_1111 <= {{m_axi_gmem1_0_RDATA[159:144]}};
        e1_reg_1021 <= e1_fu_711_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln103_fu_678_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_2 = 12'd0;
    end else begin
        ap_sig_allocacmp_p_2 = p_fu_156;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg))) begin
        gmem1_blk_n_R = m_axi_gmem1_0_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg))) begin
        m_axi_gmem1_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_d1 = e1_9_reg_1111;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_10_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_d1 = e1_8_reg_1101;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_11_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_d1 = e1_7_reg_1091;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_12_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_d1 = e1_6_reg_1081;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_13_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_d1 = e1_5_reg_1071;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_14_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_d1 = e1_4_reg_1061;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_15_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_d1 = e1_3_reg_1051;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_16_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_d1 = e1_2_reg_1041;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_17_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_d1 = e1_1_reg_1031;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_18_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_address1 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_ce1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_d1 = e1_reg_1021;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_we1_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_d0 = e0_9_reg_1106;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_20_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_d0 = e0_8_reg_1096;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_21_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_d0 = e0_7_reg_1086;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_22_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_d0 = e0_6_reg_1076;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_23_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_d0 = e0_5_reg_1066;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_24_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_d0 = e0_4_reg_1056;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_25_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_d0 = e0_3_reg_1046;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_26_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_d0 = e0_2_reg_1036;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_27_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_d0 = e0_1_reg_1026;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_28_we0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_address0 = zext_ln103_fu_955_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_d0 = e0_reg_1016;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_we0_local;

assign add_ln103_fu_684_p2 = (ap_sig_allocacmp_p_2 + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign e0_fu_707_p1 = m_axi_gmem0_0_RDATA[15:0];

assign e1_fu_711_p1 = m_axi_gmem1_0_RDATA[15:0];

assign icmp_ln103_fu_678_p2 = ((ap_sig_allocacmp_p_2 == 12'd3072) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 256'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 32'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWADDR = 64'd0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 32'd0;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_AWVALID = 1'b0;

assign m_axi_gmem1_0_BREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = 256'd0;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 32'd0;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign m_axi_gmem1_0_WVALID = 1'b0;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_address0 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_d0 = e0_10_reg_1116;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_10_we0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_address0 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_d0 = e0_11_reg_1126;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_11_we0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_address0 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_d0 = e0_12_reg_1136;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_12_we0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_address0 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_d0 = e0_13_reg_1146;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_13_we0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_address0 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_d0 = e0_14_reg_1156;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_14_we0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_address0 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_d0 = e0_15_reg_1166;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf0_banks_15_we0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_address1 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_ce1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_d1 = e1_10_reg_1121;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_10_we1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_address1 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_ce1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_d1 = e1_11_reg_1131;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_11_we1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_address1 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_ce1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_d1 = e1_12_reg_1141;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_12_we1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_address1 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_ce1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_d1 = e1_13_reg_1151;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_13_we1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_address1 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_ce1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_d1 = e1_14_reg_1161;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_14_we1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_address1 = zext_ln103_fu_955_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_ce1_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_d1 = e1_15_reg_1171;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1 = p_ZZ22activation_acceleratorPtS_S_iiE10buf1_banks_15_we1_local;

assign zext_ln103_fu_955_p1 = p_2_reg_1007_pp0_iter1_reg;

endmodule //activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_103_1
