// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_657_46 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        sext_ln657,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_q0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_q0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_q0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_q0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_q0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_q0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [255:0] m_axi_gmem2_0_WDATA;
output  [31:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [255:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [8:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [58:0] sext_ln657;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_q0;
output  [11:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0;
input  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_q0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0;
input  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_q0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0;
input  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_q0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0;
input  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_q0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0;
input  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_q0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0;
input  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_q0;
output  [11:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0;
input  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_q0;

reg ap_idle;
reg m_axi_gmem2_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln657_fu_320_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem2_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] e_reg_480;
reg   [15:0] e_1_reg_485;
reg   [15:0] e_2_reg_490;
reg   [15:0] e_3_reg_495;
reg   [15:0] e_4_reg_500;
reg   [15:0] e_5_reg_505;
reg   [15:0] e_6_reg_510;
reg   [15:0] e_7_reg_515;
reg   [15:0] e_8_reg_520;
reg   [15:0] e_9_reg_525;
reg   [15:0] e_10_reg_530;
reg   [15:0] e_11_reg_535;
reg   [15:0] e_12_reg_540;
reg   [15:0] e_13_reg_545;
reg   [15:0] e_14_reg_550;
reg   [15:0] e_15_reg_555;
wire   [63:0] zext_ln657_fu_332_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [11:0] p_fu_82;
wire   [11:0] add_ln657_fu_326_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_p_1;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local;
reg    activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local;
reg    p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 p_fu_82 = 12'd0;
#0 ap_done_reg = 1'b0;
end

activation_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln657_fu_320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            p_fu_82 <= add_ln657_fu_326_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_82 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        e_10_reg_530 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_q0;
        e_11_reg_535 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_q0;
        e_12_reg_540 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_q0;
        e_13_reg_545 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_q0;
        e_14_reg_550 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_q0;
        e_15_reg_555 <= p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_q0;
        e_1_reg_485 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_q0;
        e_2_reg_490 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_q0;
        e_3_reg_495 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_q0;
        e_4_reg_500 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_q0;
        e_5_reg_505 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_q0;
        e_6_reg_510 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_q0;
        e_7_reg_515 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_q0;
        e_8_reg_520 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_q0;
        e_9_reg_525 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_q0;
        e_reg_480 <= activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln657_fu_320_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_p_1 = 12'd0;
    end else begin
        ap_sig_allocacmp_p_1 = p_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem2_blk_n_W = m_axi_gmem2_0_WREADY;
    end else begin
        gmem2_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem2_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem2_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0_local;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0 = zext_ln657_fu_332_p1;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0 = activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0_local;

assign add_ln657_fu_326_p2 = (ap_sig_allocacmp_p_1 + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem2_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem2_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem2_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln657_fu_320_p2 = ((ap_sig_allocacmp_p_1 == 12'd3072) ? 1'b1 : 1'b0);

assign m_axi_gmem2_0_ARADDR = 64'd0;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = 32'd0;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_ARVALID = 1'b0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_RREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = {{{{{{{{{{{{{{{{e_15_reg_555}, {e_14_reg_550}}, {e_13_reg_545}}, {e_12_reg_540}}, {e_11_reg_535}}, {e_10_reg_530}}, {e_9_reg_525}}, {e_8_reg_520}}, {e_7_reg_515}}, {e_6_reg_510}}, {e_5_reg_505}}, {e_4_reg_500}}, {e_3_reg_495}}, {e_2_reg_490}}, {e_1_reg_485}}, {e_reg_480}};

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 32'd4294967295;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_address0 = zext_ln657_fu_332_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_10_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_address0 = zext_ln657_fu_332_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_11_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_address0 = zext_ln657_fu_332_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_12_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_address0 = zext_ln657_fu_332_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_13_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_address0 = zext_ln657_fu_332_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_14_ce0_local;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_address0 = zext_ln657_fu_332_p1;

assign p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0 = p_ZZ22activation_acceleratorPtS_S_iiE10buf2_banks_15_ce0_local;

assign zext_ln657_fu_332_p1 = ap_sig_allocacmp_p_1;

endmodule //activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_657_46
