// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_lut_erf (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
output  [31:0] ap_return;

wire   [7:0] erf_lut_address0;
wire   [31:0] erf_lut_q0;
wire   [7:0] erf_lut_address1;
wire   [31:0] erf_lut_q1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln35_fu_185_p2;
reg   [0:0] or_ln35_reg_419;
reg   [0:0] or_ln35_reg_419_pp0_iter1_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter2_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter3_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter4_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter5_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter6_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter7_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter8_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter9_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter10_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter11_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter12_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter13_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter14_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter15_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter16_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter17_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter18_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter19_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter20_reg;
reg   [0:0] or_ln35_reg_419_pp0_iter21_reg;
wire   [0:0] grp_fu_137_p2;
reg   [0:0] cmp_reg_425;
reg   [0:0] cmp_reg_425_pp0_iter2_reg;
reg   [0:0] cmp_reg_425_pp0_iter3_reg;
reg   [0:0] cmp_reg_425_pp0_iter4_reg;
reg   [0:0] cmp_reg_425_pp0_iter5_reg;
reg   [0:0] cmp_reg_425_pp0_iter6_reg;
reg   [0:0] cmp_reg_425_pp0_iter7_reg;
reg   [0:0] cmp_reg_425_pp0_iter8_reg;
reg   [0:0] cmp_reg_425_pp0_iter9_reg;
reg   [0:0] cmp_reg_425_pp0_iter10_reg;
reg   [0:0] cmp_reg_425_pp0_iter11_reg;
reg   [0:0] cmp_reg_425_pp0_iter12_reg;
reg   [0:0] cmp_reg_425_pp0_iter13_reg;
reg   [0:0] cmp_reg_425_pp0_iter14_reg;
reg   [0:0] cmp_reg_425_pp0_iter15_reg;
reg   [0:0] cmp_reg_425_pp0_iter16_reg;
reg   [0:0] cmp_reg_425_pp0_iter17_reg;
reg   [0:0] cmp_reg_425_pp0_iter18_reg;
reg   [0:0] cmp_reg_425_pp0_iter19_reg;
reg   [0:0] cmp_reg_425_pp0_iter20_reg;
reg   [0:0] cmp_reg_425_pp0_iter21_reg;
wire   [0:0] grp_fu_143_p2;
reg   [0:0] tmp_6_reg_432;
reg   [0:0] tmp_6_reg_432_pp0_iter2_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter3_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter4_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter5_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter6_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter7_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter8_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter9_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter10_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter11_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter12_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter13_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter14_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter15_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter16_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter17_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter18_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter19_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter20_reg;
reg   [0:0] tmp_6_reg_432_pp0_iter21_reg;
wire   [0:0] grp_fu_149_p2;
reg   [0:0] tmp_8_reg_437;
reg   [0:0] tmp_8_reg_437_pp0_iter2_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter3_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter4_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter5_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter6_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter7_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter8_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter9_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter10_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter11_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter12_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter13_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter14_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter15_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter16_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter17_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter18_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter19_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter20_reg;
reg   [0:0] tmp_8_reg_437_pp0_iter21_reg;
wire   [31:0] grp_fu_107_p2;
reg   [31:0] sub_reg_442;
wire   [31:0] grp_fu_125_p2;
reg   [31:0] idx_f_reg_447;
reg   [31:0] idx_f_reg_447_pp0_iter7_reg;
reg   [31:0] idx_f_reg_447_pp0_iter8_reg;
reg   [31:0] idx_f_reg_447_pp0_iter9_reg;
reg   [31:0] idx_f_reg_447_pp0_iter10_reg;
reg   [31:0] idx_f_reg_447_pp0_iter11_reg;
reg   [0:0] xs_sign_reg_453;
wire   [31:0] val_fu_304_p3;
reg   [31:0] val_reg_458;
wire   [31:0] result_fu_317_p3;
reg   [31:0] result_reg_464;
reg   [31:0] result_reg_464_pp0_iter9_reg;
wire   [7:0] trunc_ln58_fu_324_p1;
reg   [7:0] trunc_ln58_reg_470;
reg   [7:0] trunc_ln58_reg_470_pp0_iter9_reg;
wire   [31:0] grp_fu_134_p1;
reg   [31:0] conv7_reg_485;
reg   [31:0] erf_lut_load_reg_490;
reg   [31:0] erf_lut_load_reg_490_pp0_iter12_reg;
reg   [31:0] erf_lut_load_reg_490_pp0_iter13_reg;
reg   [31:0] erf_lut_load_reg_490_pp0_iter14_reg;
reg   [31:0] erf_lut_load_reg_490_pp0_iter15_reg;
reg   [31:0] erf_lut_load_reg_490_pp0_iter16_reg;
reg   [31:0] erf_lut_load_reg_490_pp0_iter17_reg;
reg   [31:0] erf_lut_load_reg_490_pp0_iter18_reg;
reg   [31:0] erf_lut_load_1_reg_496;
wire   [31:0] grp_fu_113_p2;
reg   [31:0] ratio_reg_501;
wire   [31:0] grp_fu_117_p2;
reg   [31:0] sub2_reg_506;
wire   [31:0] grp_fu_130_p2;
reg   [31:0] mul_reg_511;
wire   [63:0] zext_ln43_fu_328_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln43_1_fu_337_p1;
reg    erf_lut_ce1_local;
reg    erf_lut_ce0_local;
wire   [31:0] bitcast_ln35_fu_155_p1;
wire   [7:0] tmp_5_fu_159_p4;
wire   [22:0] trunc_ln35_fu_169_p1;
wire   [0:0] icmp_ln35_1_fu_179_p2;
wire   [0:0] icmp_ln35_fu_173_p2;
wire   [31:0] data_fu_191_p1;
wire   [22:0] trunc_ln342_fu_210_p1;
wire   [24:0] mantissa_fu_214_p4;
wire   [7:0] xs_exp_fu_202_p3;
wire   [8:0] zext_ln317_fu_228_p1;
wire   [8:0] add_ln317_fu_232_p2;
wire   [7:0] sub_ln18_fu_246_p2;
wire   [0:0] tmp_fu_238_p3;
wire  signed [8:0] sext_ln18_fu_252_p1;
wire   [8:0] select_ln18_fu_256_p3;
wire  signed [31:0] sext_ln18_2_fu_264_p1;
wire   [78:0] zext_ln15_fu_224_p1;
wire   [78:0] zext_ln18_fu_268_p1;
wire   [78:0] lshr_ln18_fu_272_p2;
wire   [78:0] shl_ln18_fu_278_p2;
wire   [31:0] tmp_7_fu_284_p4;
wire   [31:0] tmp_9_fu_294_p4;
wire   [31:0] result_4_fu_312_p2;
wire   [7:0] add_ln43_fu_332_p2;
wire   [0:0] and_ln35_fu_342_p2;
wire   [0:0] xor_ln33_fu_350_p2;
wire   [0:0] or_ln35_1_fu_361_p2;
wire   [0:0] and_ln36_fu_346_p2;
wire   [0:0] xor_ln35_fu_366_p2;
wire   [0:0] and_ln35_1_fu_355_p2;
wire   [0:0] and_ln36_1_fu_372_p2;
wire   [31:0] grp_fu_121_p2;
wire   [31:0] retval_fu_387_p9;
wire   [2:0] retval_fu_387_p10;
wire    ap_block_pp0_stage0_00001;
wire   [31:0] retval_fu_387_p11;
reg   [31:0] x_int_reg;
wire  signed [2:0] retval_fu_387_p1;
wire   [2:0] retval_fu_387_p3;
wire   [2:0] retval_fu_387_p5;
wire   [2:0] retval_fu_387_p7;
wire    ap_ce_reg;

activation_accelerator_lut_erf_erf_lut_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
erf_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(erf_lut_address0),
    .ce0(erf_lut_ce0_local),
    .q0(erf_lut_q0),
    .address1(erf_lut_address1),
    .ce1(erf_lut_ce1_local),
    .q1(erf_lut_q1)
);

activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U167(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd1082130432),
    .ce(1'b1),
    .dout(grp_fu_107_p2)
);

activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U168(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(idx_f_reg_447_pp0_iter11_reg),
    .din1(conv7_reg_485),
    .ce(1'b1),
    .dout(grp_fu_113_p2)
);

activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U169(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(erf_lut_load_1_reg_496),
    .din1(erf_lut_load_reg_490),
    .ce(1'b1),
    .dout(grp_fu_117_p2)
);

activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U170(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(erf_lut_load_reg_490_pp0_iter18_reg),
    .din1(mul_reg_511),
    .ce(1'b1),
    .dout(grp_fu_121_p2)
);

activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U171(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_reg_442),
    .din1(32'd1107230479),
    .ce(1'b1),
    .dout(grp_fu_125_p2)
);

activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U172(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ratio_reg_501),
    .din1(sub2_reg_506),
    .ce(1'b1),
    .dout(grp_fu_130_p2)
);

activation_accelerator_sitofp_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_4_no_dsp_1_U173(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(result_fu_317_p3),
    .ce(1'b1),
    .dout(grp_fu_134_p1)
);

activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U174(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd8),
    .dout(grp_fu_137_p2)
);

activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U175(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd3229614080),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_143_p2)
);

activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U176(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd1082130432),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_149_p2)
);

(* dissolve_hierarchy = "yes" *) activation_accelerator_sparsemux_9_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_1_U177(
    .din0(32'd2143289344),
    .din1(32'd3212836864),
    .din2(32'd1065353216),
    .din3(grp_fu_121_p2),
    .def(retval_fu_387_p9),
    .sel(retval_fu_387_p10),
    .dout(retval_fu_387_p11)
);

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        cmp_reg_425 <= grp_fu_137_p2;
        cmp_reg_425_pp0_iter10_reg <= cmp_reg_425_pp0_iter9_reg;
        cmp_reg_425_pp0_iter11_reg <= cmp_reg_425_pp0_iter10_reg;
        cmp_reg_425_pp0_iter12_reg <= cmp_reg_425_pp0_iter11_reg;
        cmp_reg_425_pp0_iter13_reg <= cmp_reg_425_pp0_iter12_reg;
        cmp_reg_425_pp0_iter14_reg <= cmp_reg_425_pp0_iter13_reg;
        cmp_reg_425_pp0_iter15_reg <= cmp_reg_425_pp0_iter14_reg;
        cmp_reg_425_pp0_iter16_reg <= cmp_reg_425_pp0_iter15_reg;
        cmp_reg_425_pp0_iter17_reg <= cmp_reg_425_pp0_iter16_reg;
        cmp_reg_425_pp0_iter18_reg <= cmp_reg_425_pp0_iter17_reg;
        cmp_reg_425_pp0_iter19_reg <= cmp_reg_425_pp0_iter18_reg;
        cmp_reg_425_pp0_iter20_reg <= cmp_reg_425_pp0_iter19_reg;
        cmp_reg_425_pp0_iter21_reg <= cmp_reg_425_pp0_iter20_reg;
        cmp_reg_425_pp0_iter2_reg <= cmp_reg_425;
        cmp_reg_425_pp0_iter3_reg <= cmp_reg_425_pp0_iter2_reg;
        cmp_reg_425_pp0_iter4_reg <= cmp_reg_425_pp0_iter3_reg;
        cmp_reg_425_pp0_iter5_reg <= cmp_reg_425_pp0_iter4_reg;
        cmp_reg_425_pp0_iter6_reg <= cmp_reg_425_pp0_iter5_reg;
        cmp_reg_425_pp0_iter7_reg <= cmp_reg_425_pp0_iter6_reg;
        cmp_reg_425_pp0_iter8_reg <= cmp_reg_425_pp0_iter7_reg;
        cmp_reg_425_pp0_iter9_reg <= cmp_reg_425_pp0_iter8_reg;
        conv7_reg_485 <= grp_fu_134_p1;
        erf_lut_load_1_reg_496 <= erf_lut_q0;
        erf_lut_load_reg_490 <= erf_lut_q1;
        erf_lut_load_reg_490_pp0_iter12_reg <= erf_lut_load_reg_490;
        erf_lut_load_reg_490_pp0_iter13_reg <= erf_lut_load_reg_490_pp0_iter12_reg;
        erf_lut_load_reg_490_pp0_iter14_reg <= erf_lut_load_reg_490_pp0_iter13_reg;
        erf_lut_load_reg_490_pp0_iter15_reg <= erf_lut_load_reg_490_pp0_iter14_reg;
        erf_lut_load_reg_490_pp0_iter16_reg <= erf_lut_load_reg_490_pp0_iter15_reg;
        erf_lut_load_reg_490_pp0_iter17_reg <= erf_lut_load_reg_490_pp0_iter16_reg;
        erf_lut_load_reg_490_pp0_iter18_reg <= erf_lut_load_reg_490_pp0_iter17_reg;
        idx_f_reg_447 <= grp_fu_125_p2;
        idx_f_reg_447_pp0_iter10_reg <= idx_f_reg_447_pp0_iter9_reg;
        idx_f_reg_447_pp0_iter11_reg <= idx_f_reg_447_pp0_iter10_reg;
        idx_f_reg_447_pp0_iter7_reg <= idx_f_reg_447;
        idx_f_reg_447_pp0_iter8_reg <= idx_f_reg_447_pp0_iter7_reg;
        idx_f_reg_447_pp0_iter9_reg <= idx_f_reg_447_pp0_iter8_reg;
        mul_reg_511 <= grp_fu_130_p2;
        or_ln35_reg_419 <= or_ln35_fu_185_p2;
        or_ln35_reg_419_pp0_iter10_reg <= or_ln35_reg_419_pp0_iter9_reg;
        or_ln35_reg_419_pp0_iter11_reg <= or_ln35_reg_419_pp0_iter10_reg;
        or_ln35_reg_419_pp0_iter12_reg <= or_ln35_reg_419_pp0_iter11_reg;
        or_ln35_reg_419_pp0_iter13_reg <= or_ln35_reg_419_pp0_iter12_reg;
        or_ln35_reg_419_pp0_iter14_reg <= or_ln35_reg_419_pp0_iter13_reg;
        or_ln35_reg_419_pp0_iter15_reg <= or_ln35_reg_419_pp0_iter14_reg;
        or_ln35_reg_419_pp0_iter16_reg <= or_ln35_reg_419_pp0_iter15_reg;
        or_ln35_reg_419_pp0_iter17_reg <= or_ln35_reg_419_pp0_iter16_reg;
        or_ln35_reg_419_pp0_iter18_reg <= or_ln35_reg_419_pp0_iter17_reg;
        or_ln35_reg_419_pp0_iter19_reg <= or_ln35_reg_419_pp0_iter18_reg;
        or_ln35_reg_419_pp0_iter1_reg <= or_ln35_reg_419;
        or_ln35_reg_419_pp0_iter20_reg <= or_ln35_reg_419_pp0_iter19_reg;
        or_ln35_reg_419_pp0_iter21_reg <= or_ln35_reg_419_pp0_iter20_reg;
        or_ln35_reg_419_pp0_iter2_reg <= or_ln35_reg_419_pp0_iter1_reg;
        or_ln35_reg_419_pp0_iter3_reg <= or_ln35_reg_419_pp0_iter2_reg;
        or_ln35_reg_419_pp0_iter4_reg <= or_ln35_reg_419_pp0_iter3_reg;
        or_ln35_reg_419_pp0_iter5_reg <= or_ln35_reg_419_pp0_iter4_reg;
        or_ln35_reg_419_pp0_iter6_reg <= or_ln35_reg_419_pp0_iter5_reg;
        or_ln35_reg_419_pp0_iter7_reg <= or_ln35_reg_419_pp0_iter6_reg;
        or_ln35_reg_419_pp0_iter8_reg <= or_ln35_reg_419_pp0_iter7_reg;
        or_ln35_reg_419_pp0_iter9_reg <= or_ln35_reg_419_pp0_iter8_reg;
        ratio_reg_501 <= grp_fu_113_p2;
        result_reg_464 <= result_fu_317_p3;
        result_reg_464_pp0_iter9_reg <= result_reg_464;
        sub2_reg_506 <= grp_fu_117_p2;
        sub_reg_442 <= grp_fu_107_p2;
        tmp_6_reg_432 <= grp_fu_143_p2;
        tmp_6_reg_432_pp0_iter10_reg <= tmp_6_reg_432_pp0_iter9_reg;
        tmp_6_reg_432_pp0_iter11_reg <= tmp_6_reg_432_pp0_iter10_reg;
        tmp_6_reg_432_pp0_iter12_reg <= tmp_6_reg_432_pp0_iter11_reg;
        tmp_6_reg_432_pp0_iter13_reg <= tmp_6_reg_432_pp0_iter12_reg;
        tmp_6_reg_432_pp0_iter14_reg <= tmp_6_reg_432_pp0_iter13_reg;
        tmp_6_reg_432_pp0_iter15_reg <= tmp_6_reg_432_pp0_iter14_reg;
        tmp_6_reg_432_pp0_iter16_reg <= tmp_6_reg_432_pp0_iter15_reg;
        tmp_6_reg_432_pp0_iter17_reg <= tmp_6_reg_432_pp0_iter16_reg;
        tmp_6_reg_432_pp0_iter18_reg <= tmp_6_reg_432_pp0_iter17_reg;
        tmp_6_reg_432_pp0_iter19_reg <= tmp_6_reg_432_pp0_iter18_reg;
        tmp_6_reg_432_pp0_iter20_reg <= tmp_6_reg_432_pp0_iter19_reg;
        tmp_6_reg_432_pp0_iter21_reg <= tmp_6_reg_432_pp0_iter20_reg;
        tmp_6_reg_432_pp0_iter2_reg <= tmp_6_reg_432;
        tmp_6_reg_432_pp0_iter3_reg <= tmp_6_reg_432_pp0_iter2_reg;
        tmp_6_reg_432_pp0_iter4_reg <= tmp_6_reg_432_pp0_iter3_reg;
        tmp_6_reg_432_pp0_iter5_reg <= tmp_6_reg_432_pp0_iter4_reg;
        tmp_6_reg_432_pp0_iter6_reg <= tmp_6_reg_432_pp0_iter5_reg;
        tmp_6_reg_432_pp0_iter7_reg <= tmp_6_reg_432_pp0_iter6_reg;
        tmp_6_reg_432_pp0_iter8_reg <= tmp_6_reg_432_pp0_iter7_reg;
        tmp_6_reg_432_pp0_iter9_reg <= tmp_6_reg_432_pp0_iter8_reg;
        tmp_8_reg_437 <= grp_fu_149_p2;
        tmp_8_reg_437_pp0_iter10_reg <= tmp_8_reg_437_pp0_iter9_reg;
        tmp_8_reg_437_pp0_iter11_reg <= tmp_8_reg_437_pp0_iter10_reg;
        tmp_8_reg_437_pp0_iter12_reg <= tmp_8_reg_437_pp0_iter11_reg;
        tmp_8_reg_437_pp0_iter13_reg <= tmp_8_reg_437_pp0_iter12_reg;
        tmp_8_reg_437_pp0_iter14_reg <= tmp_8_reg_437_pp0_iter13_reg;
        tmp_8_reg_437_pp0_iter15_reg <= tmp_8_reg_437_pp0_iter14_reg;
        tmp_8_reg_437_pp0_iter16_reg <= tmp_8_reg_437_pp0_iter15_reg;
        tmp_8_reg_437_pp0_iter17_reg <= tmp_8_reg_437_pp0_iter16_reg;
        tmp_8_reg_437_pp0_iter18_reg <= tmp_8_reg_437_pp0_iter17_reg;
        tmp_8_reg_437_pp0_iter19_reg <= tmp_8_reg_437_pp0_iter18_reg;
        tmp_8_reg_437_pp0_iter20_reg <= tmp_8_reg_437_pp0_iter19_reg;
        tmp_8_reg_437_pp0_iter21_reg <= tmp_8_reg_437_pp0_iter20_reg;
        tmp_8_reg_437_pp0_iter2_reg <= tmp_8_reg_437;
        tmp_8_reg_437_pp0_iter3_reg <= tmp_8_reg_437_pp0_iter2_reg;
        tmp_8_reg_437_pp0_iter4_reg <= tmp_8_reg_437_pp0_iter3_reg;
        tmp_8_reg_437_pp0_iter5_reg <= tmp_8_reg_437_pp0_iter4_reg;
        tmp_8_reg_437_pp0_iter6_reg <= tmp_8_reg_437_pp0_iter5_reg;
        tmp_8_reg_437_pp0_iter7_reg <= tmp_8_reg_437_pp0_iter6_reg;
        tmp_8_reg_437_pp0_iter8_reg <= tmp_8_reg_437_pp0_iter7_reg;
        tmp_8_reg_437_pp0_iter9_reg <= tmp_8_reg_437_pp0_iter8_reg;
        trunc_ln58_reg_470 <= trunc_ln58_fu_324_p1;
        trunc_ln58_reg_470_pp0_iter9_reg <= trunc_ln58_reg_470;
        val_reg_458 <= val_fu_304_p3;
        xs_sign_reg_453 <= data_fu_191_p1[32'd31];
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        erf_lut_ce0_local = 1'b1;
    end else begin
        erf_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        erf_lut_ce1_local = 1'b1;
    end else begin
        erf_lut_ce1_local = 1'b0;
    end
end

assign add_ln317_fu_232_p2 = ($signed(zext_ln317_fu_228_p1) + $signed(9'd385));

assign add_ln43_fu_332_p2 = (trunc_ln58_reg_470_pp0_iter9_reg + 8'd1);

assign and_ln35_1_fu_355_p2 = (xor_ln33_fu_350_p2 & and_ln35_fu_342_p2);

assign and_ln35_fu_342_p2 = (tmp_6_reg_432_pp0_iter21_reg & or_ln35_reg_419_pp0_iter21_reg);

assign and_ln36_1_fu_372_p2 = (xor_ln35_fu_366_p2 & and_ln36_fu_346_p2);

assign and_ln36_fu_346_p2 = (tmp_8_reg_437_pp0_iter21_reg & or_ln35_reg_419_pp0_iter21_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = retval_fu_387_p11;

assign bitcast_ln35_fu_155_p1 = x_int_reg;

assign data_fu_191_p1 = idx_f_reg_447;

assign erf_lut_address0 = zext_ln43_1_fu_337_p1;

assign erf_lut_address1 = zext_ln43_fu_328_p1;

assign icmp_ln35_1_fu_179_p2 = ((trunc_ln35_fu_169_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_173_p2 = ((tmp_5_fu_159_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_272_p2 = zext_ln15_fu_224_p1 >> zext_ln18_fu_268_p1;

assign mantissa_fu_214_p4 = {{{{1'd1}, {trunc_ln342_fu_210_p1}}}, {1'd0}};

assign or_ln35_1_fu_361_p2 = (cmp_reg_425_pp0_iter21_reg | and_ln35_fu_342_p2);

assign or_ln35_fu_185_p2 = (icmp_ln35_fu_173_p2 | icmp_ln35_1_fu_179_p2);

assign result_4_fu_312_p2 = (32'd0 - val_reg_458);

assign result_fu_317_p3 = ((xs_sign_reg_453[0:0] == 1'b1) ? result_4_fu_312_p2 : val_reg_458);

assign retval_fu_387_p10 = {{{cmp_reg_425_pp0_iter21_reg}, {and_ln35_1_fu_355_p2}}, {and_ln36_1_fu_372_p2}};

assign retval_fu_387_p9 = 'bx;

assign select_ln18_fu_256_p3 = ((tmp_fu_238_p3[0:0] == 1'b1) ? sext_ln18_fu_252_p1 : add_ln317_fu_232_p2);

assign sext_ln18_2_fu_264_p1 = $signed(select_ln18_fu_256_p3);

assign sext_ln18_fu_252_p1 = $signed(sub_ln18_fu_246_p2);

assign shl_ln18_fu_278_p2 = zext_ln15_fu_224_p1 << zext_ln18_fu_268_p1;

assign sub_ln18_fu_246_p2 = (8'd127 - xs_exp_fu_202_p3);

assign tmp_5_fu_159_p4 = {{bitcast_ln35_fu_155_p1[30:23]}};

assign tmp_7_fu_284_p4 = {{lshr_ln18_fu_272_p2[55:24]}};

assign tmp_9_fu_294_p4 = {{shl_ln18_fu_278_p2[55:24]}};

assign tmp_fu_238_p3 = add_ln317_fu_232_p2[32'd8];

assign trunc_ln342_fu_210_p1 = data_fu_191_p1[22:0];

assign trunc_ln35_fu_169_p1 = bitcast_ln35_fu_155_p1[22:0];

assign trunc_ln58_fu_324_p1 = result_fu_317_p3[7:0];

assign val_fu_304_p3 = ((tmp_fu_238_p3[0:0] == 1'b1) ? tmp_7_fu_284_p4 : tmp_9_fu_294_p4);

assign xor_ln33_fu_350_p2 = (cmp_reg_425_pp0_iter21_reg ^ 1'd1);

assign xor_ln35_fu_366_p2 = (or_ln35_1_fu_361_p2 ^ 1'd1);

assign xs_exp_fu_202_p3 = {{data_fu_191_p1[30:23]}};

assign zext_ln15_fu_224_p1 = mantissa_fu_214_p4;

assign zext_ln18_fu_268_p1 = $unsigned(sext_ln18_2_fu_264_p1);

assign zext_ln317_fu_228_p1 = xs_exp_fu_202_p3;

assign zext_ln43_1_fu_337_p1 = add_ln43_fu_332_p2;

assign zext_ln43_fu_328_p1 = result_reg_464_pp0_iter9_reg;

endmodule //activation_accelerator_lut_erf
