// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_lut_exp (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

wire   [8:0] exp_lut_address0;
wire   [31:0] exp_lut_q0;
wire   [8:0] exp_lut_address1;
wire   [31:0] exp_lut_q1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln19_fu_183_p2;
reg   [0:0] or_ln19_reg_417;
reg   [0:0] or_ln19_reg_417_pp0_iter1_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter2_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter3_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter4_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter5_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter6_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter7_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter8_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter9_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter10_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter11_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter12_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter13_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter14_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter15_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter16_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter17_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter18_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter19_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter20_reg;
reg   [0:0] or_ln19_reg_417_pp0_iter21_reg;
wire   [0:0] grp_fu_135_p2;
reg   [0:0] cmp_reg_423;
reg   [0:0] cmp_reg_423_pp0_iter2_reg;
reg   [0:0] cmp_reg_423_pp0_iter3_reg;
reg   [0:0] cmp_reg_423_pp0_iter4_reg;
reg   [0:0] cmp_reg_423_pp0_iter5_reg;
reg   [0:0] cmp_reg_423_pp0_iter6_reg;
reg   [0:0] cmp_reg_423_pp0_iter7_reg;
reg   [0:0] cmp_reg_423_pp0_iter8_reg;
reg   [0:0] cmp_reg_423_pp0_iter9_reg;
reg   [0:0] cmp_reg_423_pp0_iter10_reg;
reg   [0:0] cmp_reg_423_pp0_iter11_reg;
reg   [0:0] cmp_reg_423_pp0_iter12_reg;
reg   [0:0] cmp_reg_423_pp0_iter13_reg;
reg   [0:0] cmp_reg_423_pp0_iter14_reg;
reg   [0:0] cmp_reg_423_pp0_iter15_reg;
reg   [0:0] cmp_reg_423_pp0_iter16_reg;
reg   [0:0] cmp_reg_423_pp0_iter17_reg;
reg   [0:0] cmp_reg_423_pp0_iter18_reg;
reg   [0:0] cmp_reg_423_pp0_iter19_reg;
reg   [0:0] cmp_reg_423_pp0_iter20_reg;
reg   [0:0] cmp_reg_423_pp0_iter21_reg;
wire   [0:0] grp_fu_141_p2;
reg   [0:0] tmp_2_reg_430;
reg   [0:0] tmp_2_reg_430_pp0_iter2_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter3_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter4_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter5_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter6_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter7_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter8_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter9_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter10_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter11_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter12_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter13_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter14_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter15_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter16_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter17_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter18_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter19_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter20_reg;
reg   [0:0] tmp_2_reg_430_pp0_iter21_reg;
wire   [0:0] grp_fu_147_p2;
reg   [0:0] tmp_4_reg_435;
reg   [0:0] tmp_4_reg_435_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter6_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter7_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter8_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter9_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter10_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter11_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter12_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter13_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter14_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter15_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter16_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter17_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter18_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter19_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter20_reg;
reg   [0:0] tmp_4_reg_435_pp0_iter21_reg;
wire   [31:0] grp_fu_105_p2;
reg   [31:0] sub_reg_440;
wire   [31:0] grp_fu_123_p2;
reg   [31:0] idx_f_reg_445;
reg   [31:0] idx_f_reg_445_pp0_iter7_reg;
reg   [31:0] idx_f_reg_445_pp0_iter8_reg;
reg   [31:0] idx_f_reg_445_pp0_iter9_reg;
reg   [31:0] idx_f_reg_445_pp0_iter10_reg;
reg   [31:0] idx_f_reg_445_pp0_iter11_reg;
reg   [0:0] xs_sign_reg_451;
wire   [31:0] val_fu_302_p3;
reg   [31:0] val_reg_456;
wire   [31:0] result_fu_315_p3;
reg   [31:0] result_reg_462;
reg   [31:0] result_reg_462_pp0_iter9_reg;
wire   [8:0] trunc_ln58_fu_322_p1;
reg   [8:0] trunc_ln58_reg_468;
reg   [8:0] trunc_ln58_reg_468_pp0_iter9_reg;
wire   [31:0] grp_fu_132_p1;
reg   [31:0] conv7_reg_483;
reg   [31:0] exp_lut_load_reg_488;
reg   [31:0] exp_lut_load_reg_488_pp0_iter12_reg;
reg   [31:0] exp_lut_load_reg_488_pp0_iter13_reg;
reg   [31:0] exp_lut_load_reg_488_pp0_iter14_reg;
reg   [31:0] exp_lut_load_reg_488_pp0_iter15_reg;
reg   [31:0] exp_lut_load_reg_488_pp0_iter16_reg;
reg   [31:0] exp_lut_load_reg_488_pp0_iter17_reg;
reg   [31:0] exp_lut_load_reg_488_pp0_iter18_reg;
reg   [31:0] exp_lut_load_1_reg_494;
wire   [31:0] grp_fu_111_p2;
reg   [31:0] ratio_reg_499;
wire   [31:0] grp_fu_115_p2;
reg   [31:0] sub1_reg_504;
wire   [31:0] grp_fu_128_p2;
reg   [31:0] mul_reg_509;
wire   [63:0] zext_ln28_fu_326_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln28_1_fu_335_p1;
reg    exp_lut_ce1_local;
reg    exp_lut_ce0_local;
wire   [31:0] bitcast_ln19_fu_153_p1;
wire   [7:0] tmp_1_fu_157_p4;
wire   [22:0] trunc_ln19_fu_167_p1;
wire   [0:0] icmp_ln19_1_fu_177_p2;
wire   [0:0] icmp_ln19_fu_171_p2;
wire   [31:0] data_fu_189_p1;
wire   [22:0] trunc_ln342_fu_208_p1;
wire   [24:0] mantissa_fu_212_p4;
wire   [7:0] xs_exp_fu_200_p3;
wire   [8:0] zext_ln317_fu_226_p1;
wire   [8:0] add_ln317_fu_230_p2;
wire   [7:0] sub_ln18_fu_244_p2;
wire   [0:0] tmp_fu_236_p3;
wire  signed [8:0] sext_ln18_fu_250_p1;
wire   [8:0] select_ln18_fu_254_p3;
wire  signed [31:0] sext_ln18_1_fu_262_p1;
wire   [78:0] zext_ln15_fu_222_p1;
wire   [78:0] zext_ln18_fu_266_p1;
wire   [78:0] lshr_ln18_fu_270_p2;
wire   [78:0] shl_ln18_fu_276_p2;
wire   [31:0] tmp_3_fu_282_p4;
wire   [31:0] tmp_5_fu_292_p4;
wire   [31:0] result_2_fu_310_p2;
wire   [8:0] add_ln28_fu_330_p2;
wire   [0:0] and_ln20_fu_344_p2;
wire   [0:0] or_ln20_fu_348_p2;
wire   [0:0] and_ln19_fu_340_p2;
wire   [0:0] or_ln20_1_fu_353_p2;
wire   [0:0] xor_ln19_fu_365_p2;
wire   [0:0] xor_ln20_fu_359_p2;
wire   [0:0] and_ln19_1_fu_370_p2;
wire   [31:0] grp_fu_119_p2;
wire   [31:0] retval_fu_385_p9;
wire   [2:0] retval_fu_385_p10;
reg    grp_fu_105_ce;
reg    grp_fu_111_ce;
reg    grp_fu_115_ce;
reg    grp_fu_119_ce;
reg    grp_fu_123_ce;
reg    grp_fu_128_ce;
reg    grp_fu_132_ce;
reg    grp_fu_135_ce;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_141_ce;
reg    grp_fu_147_ce;
wire   [31:0] retval_fu_385_p11;
reg    ap_ce_reg;
reg   [31:0] x_int_reg;
reg   [31:0] ap_return_int_reg;
wire  signed [2:0] retval_fu_385_p1;
wire   [2:0] retval_fu_385_p3;
wire   [2:0] retval_fu_385_p5;
wire   [2:0] retval_fu_385_p7;

activation_accelerator_lut_exp_exp_lut_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
exp_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_lut_address0),
    .ce0(exp_lut_ce0_local),
    .q0(exp_lut_q0),
    .address1(exp_lut_address1),
    .ce1(exp_lut_ce1_local),
    .q1(exp_lut_q1)
);

activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U639(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd1098907648),
    .ce(grp_fu_105_ce),
    .dout(grp_fu_105_p2)
);

activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U640(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(idx_f_reg_445_pp0_iter11_reg),
    .din1(conv7_reg_483),
    .ce(grp_fu_111_ce),
    .dout(grp_fu_111_p2)
);

activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U641(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(exp_lut_load_1_reg_494),
    .din1(exp_lut_load_reg_488),
    .ce(grp_fu_115_ce),
    .dout(grp_fu_115_p2)
);

activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U642(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(exp_lut_load_reg_488_pp0_iter18_reg),
    .din1(mul_reg_509),
    .ce(grp_fu_119_ce),
    .dout(grp_fu_119_p2)
);

activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U643(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_reg_440),
    .din1(32'd1107262815),
    .ce(grp_fu_123_ce),
    .dout(grp_fu_123_p2)
);

activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U644(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ratio_reg_499),
    .din1(sub1_reg_504),
    .ce(grp_fu_128_ce),
    .dout(grp_fu_128_p2)
);

activation_accelerator_sitofp_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_4_no_dsp_1_U645(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(result_fu_315_p3),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p1)
);

activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U646(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd0),
    .ce(grp_fu_135_ce),
    .opcode(5'd8),
    .dout(grp_fu_135_p2)
);

activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U647(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd3246391296),
    .ce(grp_fu_141_ce),
    .opcode(5'd5),
    .dout(grp_fu_141_p2)
);

activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U648(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_int_reg),
    .din1(32'd0),
    .ce(grp_fu_147_ce),
    .opcode(5'd3),
    .dout(grp_fu_147_p2)
);

(* dissolve_hierarchy = "yes" *) activation_accelerator_sparsemux_9_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_1_U649(
    .din0(32'd2143289344),
    .din1(grp_fu_119_p2),
    .din2(32'd0),
    .din3(32'd1065353216),
    .def(retval_fu_385_p9),
    .sel(retval_fu_385_p10),
    .dout(retval_fu_385_p11)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= retval_fu_385_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        cmp_reg_423 <= grp_fu_135_p2;
        cmp_reg_423_pp0_iter10_reg <= cmp_reg_423_pp0_iter9_reg;
        cmp_reg_423_pp0_iter11_reg <= cmp_reg_423_pp0_iter10_reg;
        cmp_reg_423_pp0_iter12_reg <= cmp_reg_423_pp0_iter11_reg;
        cmp_reg_423_pp0_iter13_reg <= cmp_reg_423_pp0_iter12_reg;
        cmp_reg_423_pp0_iter14_reg <= cmp_reg_423_pp0_iter13_reg;
        cmp_reg_423_pp0_iter15_reg <= cmp_reg_423_pp0_iter14_reg;
        cmp_reg_423_pp0_iter16_reg <= cmp_reg_423_pp0_iter15_reg;
        cmp_reg_423_pp0_iter17_reg <= cmp_reg_423_pp0_iter16_reg;
        cmp_reg_423_pp0_iter18_reg <= cmp_reg_423_pp0_iter17_reg;
        cmp_reg_423_pp0_iter19_reg <= cmp_reg_423_pp0_iter18_reg;
        cmp_reg_423_pp0_iter20_reg <= cmp_reg_423_pp0_iter19_reg;
        cmp_reg_423_pp0_iter21_reg <= cmp_reg_423_pp0_iter20_reg;
        cmp_reg_423_pp0_iter2_reg <= cmp_reg_423;
        cmp_reg_423_pp0_iter3_reg <= cmp_reg_423_pp0_iter2_reg;
        cmp_reg_423_pp0_iter4_reg <= cmp_reg_423_pp0_iter3_reg;
        cmp_reg_423_pp0_iter5_reg <= cmp_reg_423_pp0_iter4_reg;
        cmp_reg_423_pp0_iter6_reg <= cmp_reg_423_pp0_iter5_reg;
        cmp_reg_423_pp0_iter7_reg <= cmp_reg_423_pp0_iter6_reg;
        cmp_reg_423_pp0_iter8_reg <= cmp_reg_423_pp0_iter7_reg;
        cmp_reg_423_pp0_iter9_reg <= cmp_reg_423_pp0_iter8_reg;
        conv7_reg_483 <= grp_fu_132_p1;
        exp_lut_load_1_reg_494 <= exp_lut_q0;
        exp_lut_load_reg_488 <= exp_lut_q1;
        exp_lut_load_reg_488_pp0_iter12_reg <= exp_lut_load_reg_488;
        exp_lut_load_reg_488_pp0_iter13_reg <= exp_lut_load_reg_488_pp0_iter12_reg;
        exp_lut_load_reg_488_pp0_iter14_reg <= exp_lut_load_reg_488_pp0_iter13_reg;
        exp_lut_load_reg_488_pp0_iter15_reg <= exp_lut_load_reg_488_pp0_iter14_reg;
        exp_lut_load_reg_488_pp0_iter16_reg <= exp_lut_load_reg_488_pp0_iter15_reg;
        exp_lut_load_reg_488_pp0_iter17_reg <= exp_lut_load_reg_488_pp0_iter16_reg;
        exp_lut_load_reg_488_pp0_iter18_reg <= exp_lut_load_reg_488_pp0_iter17_reg;
        idx_f_reg_445 <= grp_fu_123_p2;
        idx_f_reg_445_pp0_iter10_reg <= idx_f_reg_445_pp0_iter9_reg;
        idx_f_reg_445_pp0_iter11_reg <= idx_f_reg_445_pp0_iter10_reg;
        idx_f_reg_445_pp0_iter7_reg <= idx_f_reg_445;
        idx_f_reg_445_pp0_iter8_reg <= idx_f_reg_445_pp0_iter7_reg;
        idx_f_reg_445_pp0_iter9_reg <= idx_f_reg_445_pp0_iter8_reg;
        mul_reg_509 <= grp_fu_128_p2;
        or_ln19_reg_417 <= or_ln19_fu_183_p2;
        or_ln19_reg_417_pp0_iter10_reg <= or_ln19_reg_417_pp0_iter9_reg;
        or_ln19_reg_417_pp0_iter11_reg <= or_ln19_reg_417_pp0_iter10_reg;
        or_ln19_reg_417_pp0_iter12_reg <= or_ln19_reg_417_pp0_iter11_reg;
        or_ln19_reg_417_pp0_iter13_reg <= or_ln19_reg_417_pp0_iter12_reg;
        or_ln19_reg_417_pp0_iter14_reg <= or_ln19_reg_417_pp0_iter13_reg;
        or_ln19_reg_417_pp0_iter15_reg <= or_ln19_reg_417_pp0_iter14_reg;
        or_ln19_reg_417_pp0_iter16_reg <= or_ln19_reg_417_pp0_iter15_reg;
        or_ln19_reg_417_pp0_iter17_reg <= or_ln19_reg_417_pp0_iter16_reg;
        or_ln19_reg_417_pp0_iter18_reg <= or_ln19_reg_417_pp0_iter17_reg;
        or_ln19_reg_417_pp0_iter19_reg <= or_ln19_reg_417_pp0_iter18_reg;
        or_ln19_reg_417_pp0_iter1_reg <= or_ln19_reg_417;
        or_ln19_reg_417_pp0_iter20_reg <= or_ln19_reg_417_pp0_iter19_reg;
        or_ln19_reg_417_pp0_iter21_reg <= or_ln19_reg_417_pp0_iter20_reg;
        or_ln19_reg_417_pp0_iter2_reg <= or_ln19_reg_417_pp0_iter1_reg;
        or_ln19_reg_417_pp0_iter3_reg <= or_ln19_reg_417_pp0_iter2_reg;
        or_ln19_reg_417_pp0_iter4_reg <= or_ln19_reg_417_pp0_iter3_reg;
        or_ln19_reg_417_pp0_iter5_reg <= or_ln19_reg_417_pp0_iter4_reg;
        or_ln19_reg_417_pp0_iter6_reg <= or_ln19_reg_417_pp0_iter5_reg;
        or_ln19_reg_417_pp0_iter7_reg <= or_ln19_reg_417_pp0_iter6_reg;
        or_ln19_reg_417_pp0_iter8_reg <= or_ln19_reg_417_pp0_iter7_reg;
        or_ln19_reg_417_pp0_iter9_reg <= or_ln19_reg_417_pp0_iter8_reg;
        ratio_reg_499 <= grp_fu_111_p2;
        result_reg_462 <= result_fu_315_p3;
        result_reg_462_pp0_iter9_reg <= result_reg_462;
        sub1_reg_504 <= grp_fu_115_p2;
        sub_reg_440 <= grp_fu_105_p2;
        tmp_2_reg_430 <= grp_fu_141_p2;
        tmp_2_reg_430_pp0_iter10_reg <= tmp_2_reg_430_pp0_iter9_reg;
        tmp_2_reg_430_pp0_iter11_reg <= tmp_2_reg_430_pp0_iter10_reg;
        tmp_2_reg_430_pp0_iter12_reg <= tmp_2_reg_430_pp0_iter11_reg;
        tmp_2_reg_430_pp0_iter13_reg <= tmp_2_reg_430_pp0_iter12_reg;
        tmp_2_reg_430_pp0_iter14_reg <= tmp_2_reg_430_pp0_iter13_reg;
        tmp_2_reg_430_pp0_iter15_reg <= tmp_2_reg_430_pp0_iter14_reg;
        tmp_2_reg_430_pp0_iter16_reg <= tmp_2_reg_430_pp0_iter15_reg;
        tmp_2_reg_430_pp0_iter17_reg <= tmp_2_reg_430_pp0_iter16_reg;
        tmp_2_reg_430_pp0_iter18_reg <= tmp_2_reg_430_pp0_iter17_reg;
        tmp_2_reg_430_pp0_iter19_reg <= tmp_2_reg_430_pp0_iter18_reg;
        tmp_2_reg_430_pp0_iter20_reg <= tmp_2_reg_430_pp0_iter19_reg;
        tmp_2_reg_430_pp0_iter21_reg <= tmp_2_reg_430_pp0_iter20_reg;
        tmp_2_reg_430_pp0_iter2_reg <= tmp_2_reg_430;
        tmp_2_reg_430_pp0_iter3_reg <= tmp_2_reg_430_pp0_iter2_reg;
        tmp_2_reg_430_pp0_iter4_reg <= tmp_2_reg_430_pp0_iter3_reg;
        tmp_2_reg_430_pp0_iter5_reg <= tmp_2_reg_430_pp0_iter4_reg;
        tmp_2_reg_430_pp0_iter6_reg <= tmp_2_reg_430_pp0_iter5_reg;
        tmp_2_reg_430_pp0_iter7_reg <= tmp_2_reg_430_pp0_iter6_reg;
        tmp_2_reg_430_pp0_iter8_reg <= tmp_2_reg_430_pp0_iter7_reg;
        tmp_2_reg_430_pp0_iter9_reg <= tmp_2_reg_430_pp0_iter8_reg;
        tmp_4_reg_435 <= grp_fu_147_p2;
        tmp_4_reg_435_pp0_iter10_reg <= tmp_4_reg_435_pp0_iter9_reg;
        tmp_4_reg_435_pp0_iter11_reg <= tmp_4_reg_435_pp0_iter10_reg;
        tmp_4_reg_435_pp0_iter12_reg <= tmp_4_reg_435_pp0_iter11_reg;
        tmp_4_reg_435_pp0_iter13_reg <= tmp_4_reg_435_pp0_iter12_reg;
        tmp_4_reg_435_pp0_iter14_reg <= tmp_4_reg_435_pp0_iter13_reg;
        tmp_4_reg_435_pp0_iter15_reg <= tmp_4_reg_435_pp0_iter14_reg;
        tmp_4_reg_435_pp0_iter16_reg <= tmp_4_reg_435_pp0_iter15_reg;
        tmp_4_reg_435_pp0_iter17_reg <= tmp_4_reg_435_pp0_iter16_reg;
        tmp_4_reg_435_pp0_iter18_reg <= tmp_4_reg_435_pp0_iter17_reg;
        tmp_4_reg_435_pp0_iter19_reg <= tmp_4_reg_435_pp0_iter18_reg;
        tmp_4_reg_435_pp0_iter20_reg <= tmp_4_reg_435_pp0_iter19_reg;
        tmp_4_reg_435_pp0_iter21_reg <= tmp_4_reg_435_pp0_iter20_reg;
        tmp_4_reg_435_pp0_iter2_reg <= tmp_4_reg_435;
        tmp_4_reg_435_pp0_iter3_reg <= tmp_4_reg_435_pp0_iter2_reg;
        tmp_4_reg_435_pp0_iter4_reg <= tmp_4_reg_435_pp0_iter3_reg;
        tmp_4_reg_435_pp0_iter5_reg <= tmp_4_reg_435_pp0_iter4_reg;
        tmp_4_reg_435_pp0_iter6_reg <= tmp_4_reg_435_pp0_iter5_reg;
        tmp_4_reg_435_pp0_iter7_reg <= tmp_4_reg_435_pp0_iter6_reg;
        tmp_4_reg_435_pp0_iter8_reg <= tmp_4_reg_435_pp0_iter7_reg;
        tmp_4_reg_435_pp0_iter9_reg <= tmp_4_reg_435_pp0_iter8_reg;
        trunc_ln58_reg_468 <= trunc_ln58_fu_322_p1;
        trunc_ln58_reg_468_pp0_iter9_reg <= trunc_ln58_reg_468;
        val_reg_456 <= val_fu_302_p3;
        xs_sign_reg_451 <= data_fu_189_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = retval_fu_385_p11;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_lut_ce0_local = 1'b1;
    end else begin
        exp_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_lut_ce1_local = 1'b1;
    end else begin
        exp_lut_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_105_ce = 1'b1;
    end else begin
        grp_fu_105_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_111_ce = 1'b1;
    end else begin
        grp_fu_111_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_115_ce = 1'b1;
    end else begin
        grp_fu_115_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_119_ce = 1'b1;
    end else begin
        grp_fu_119_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_123_ce = 1'b1;
    end else begin
        grp_fu_123_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_128_ce = 1'b1;
    end else begin
        grp_fu_128_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_132_ce = 1'b1;
    end else begin
        grp_fu_132_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_135_ce = 1'b1;
    end else begin
        grp_fu_135_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_141_ce = 1'b1;
    end else begin
        grp_fu_141_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_147_ce = 1'b1;
    end else begin
        grp_fu_147_ce = 1'b0;
    end
end

assign add_ln28_fu_330_p2 = (trunc_ln58_reg_468_pp0_iter9_reg + 9'd1);

assign add_ln317_fu_230_p2 = ($signed(zext_ln317_fu_226_p1) + $signed(9'd385));

assign and_ln19_1_fu_370_p2 = (xor_ln19_fu_365_p2 & and_ln19_fu_340_p2);

assign and_ln19_fu_340_p2 = (tmp_2_reg_430_pp0_iter21_reg & or_ln19_reg_417_pp0_iter21_reg);

assign and_ln20_fu_344_p2 = (tmp_4_reg_435_pp0_iter21_reg & or_ln19_reg_417_pp0_iter21_reg);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign bitcast_ln19_fu_153_p1 = x_int_reg;

assign data_fu_189_p1 = idx_f_reg_445;

assign exp_lut_address0 = zext_ln28_1_fu_335_p1;

assign exp_lut_address1 = zext_ln28_fu_326_p1;

assign icmp_ln19_1_fu_177_p2 = ((trunc_ln19_fu_167_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_171_p2 = ((tmp_1_fu_157_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_270_p2 = zext_ln15_fu_222_p1 >> zext_ln18_fu_266_p1;

assign mantissa_fu_212_p4 = {{{{1'd1}, {trunc_ln342_fu_208_p1}}}, {1'd0}};

assign or_ln19_fu_183_p2 = (icmp_ln19_fu_171_p2 | icmp_ln19_1_fu_177_p2);

assign or_ln20_1_fu_353_p2 = (or_ln20_fu_348_p2 | and_ln19_fu_340_p2);

assign or_ln20_fu_348_p2 = (cmp_reg_423_pp0_iter21_reg | and_ln20_fu_344_p2);

assign result_2_fu_310_p2 = (32'd0 - val_reg_456);

assign result_fu_315_p3 = ((xs_sign_reg_451[0:0] == 1'b1) ? result_2_fu_310_p2 : val_reg_456);

assign retval_fu_385_p10 = {{{cmp_reg_423_pp0_iter21_reg}, {xor_ln20_fu_359_p2}}, {and_ln19_1_fu_370_p2}};

assign retval_fu_385_p9 = 'bx;

assign select_ln18_fu_254_p3 = ((tmp_fu_236_p3[0:0] == 1'b1) ? sext_ln18_fu_250_p1 : add_ln317_fu_230_p2);

assign sext_ln18_1_fu_262_p1 = $signed(select_ln18_fu_254_p3);

assign sext_ln18_fu_250_p1 = $signed(sub_ln18_fu_244_p2);

assign shl_ln18_fu_276_p2 = zext_ln15_fu_222_p1 << zext_ln18_fu_266_p1;

assign sub_ln18_fu_244_p2 = (8'd127 - xs_exp_fu_200_p3);

assign tmp_1_fu_157_p4 = {{bitcast_ln19_fu_153_p1[30:23]}};

assign tmp_3_fu_282_p4 = {{lshr_ln18_fu_270_p2[55:24]}};

assign tmp_5_fu_292_p4 = {{shl_ln18_fu_276_p2[55:24]}};

assign tmp_fu_236_p3 = add_ln317_fu_230_p2[32'd8];

assign trunc_ln19_fu_167_p1 = bitcast_ln19_fu_153_p1[22:0];

assign trunc_ln342_fu_208_p1 = data_fu_189_p1[22:0];

assign trunc_ln58_fu_322_p1 = result_fu_315_p3[8:0];

assign val_fu_302_p3 = ((tmp_fu_236_p3[0:0] == 1'b1) ? tmp_3_fu_282_p4 : tmp_5_fu_292_p4);

assign xor_ln19_fu_365_p2 = (cmp_reg_423_pp0_iter21_reg ^ 1'd1);

assign xor_ln20_fu_359_p2 = (or_ln20_1_fu_353_p2 ^ 1'd1);

assign xs_exp_fu_200_p3 = {{data_fu_189_p1[30:23]}};

assign zext_ln15_fu_222_p1 = mantissa_fu_212_p4;

assign zext_ln18_fu_266_p1 = $unsigned(sext_ln18_1_fu_262_p1);

assign zext_ln28_1_fu_335_p1 = add_ln28_fu_330_p2;

assign zext_ln28_fu_326_p1 = result_reg_462_pp0_iter9_reg;

assign zext_ln317_fu_226_p1 = xs_exp_fu_200_p3;

endmodule //activation_accelerator_lut_exp
